# https://taskfile.dev

version: "3"

tasks:
  gen:
    sources:
      - "internal/config/**/*.go"
      - "internal/generator/generator.go"
      - "internal/generator/templates/*.tmpl"
    generates:
      - "elements/html_*.go"
      - "elements/mathml_*.go"
      - "elements/svg_*.go"
    cmds:
      - go install golang.org/x/tools/cmd/goimports@latest
      - go run cmd/gen/main.go
      - time goimports -v -w elements

  test:
    deps:
      - gen
    sources:
      - "**/*.go"
    cmds:
      - go test ./...

  default:
    deps:
      - test
    silent: true
