// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements html ol is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The HTML <ol> element represents an ordered list of items, typically rendered
// as a numbered list.
type OlElement struct {
	*Element
}

// Create a new OlElement element. This will create a new element
// with the tag "ol" during rendering.
func Ol(children ...ElementRenderer) *OlElement {
	e := NewElement("ol", children...)
	e.isSelfClosing = false
	e.descendants = children
	return &OlElement{Element: e}
}

func (e *OlElement) Children(children ...ElementRenderer) *OlElement {
	e.descendants = append(e.descendants, children...)
	return e
}

func (e *OlElement) IfChildren(condition bool, children ...ElementRenderer) *OlElement {
	if condition {
		e.descendants = append(e.descendants, children...)
	}
	return e
}

func (e *OlElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *OlElement {
	if condition {
		e.descendants = append(e.descendants, trueChildren)
	} else {
		e.descendants = append(e.descendants, falseChildren)
	}
	return e
}

func (e *OlElement) BoolAttr(name string) *OlElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set(name, true)
	return e
}

func (e *OlElement) IfBoolAttr(condition bool, name string) *OlElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *OlElement) Attr(name, value string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set(name, value)
	return e
}

func (e *OlElement) IfAttr(condition bool, name, value string) *OlElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *OlElement) Text(text string) *OlElement {
	e.descendants = append(e.descendants, Text(text))
	return e
}

func (e *OlElement) Textf(format string, args ...any) *OlElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *OlElement) IfText(condition bool, text string) *OlElement {
	if condition {
		e.descendants = append(e.descendants, Text(text))
	}
	return e
}

func (e *OlElement) IfTextf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.descendants = append(e.descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *OlElement) Escaped(text string) *OlElement {
	e.descendants = append(e.descendants, Escaped(text))
	return e
}

func (e *OlElement) IfEscaped(condition bool, text string) *OlElement {
	if condition {
		e.descendants = append(e.descendants, Escaped(text))
	}
	return e
}

func (e *OlElement) Escapedf(format string, args ...any) *OlElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *OlElement) IfEscapedf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.descendants = append(e.descendants, Escapedf(format, args...))
	}
	return e
}

// Number the list backwards.
func (e *OlElement) Reversed() *OlElement {
	e.ReversedSet(true)
	return e
}

// Number the list backwards.
func (e *OlElement) IfReversed(condition bool) *OlElement {
	if condition {
		e.ReversedSet(true)
	}
	return e
}

// Number the list backwards.
// Set the attribute Reversed to the value b explicitly.
func (e *OlElement) ReversedSet(b bool) *OlElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("reversed", b)
	return e
}

// Number the list backwards.
func (e *OlElement) IfSetReversed(condition bool, b bool) *OlElement {
	if condition {
		e.ReversedSet(b)
	}
	return e
}

// Remove the attribute Reversed from the element.
// Number the list backwards.
func (e *OlElement) ReversedRemove() *OlElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("reversed")
	return e
}

// Starting value of the list.
func (e *OlElement) Start(i int) *OlElement {
	if e.intAttributes == nil {
		e.intAttributes = treemap.New[string, int]()
	}
	e.intAttributes.Set("start", i)
	return e
}

// Starting value of the list.
func (e *OlElement) IfStart(condition bool, i int) *OlElement {
	if condition {
		e.Start(i)
	}
	return e
}

// Starting value of the list.
// Remove the attribute Start from the element.
func (e *OlElement) StartRemove() *OlElement {
	if e.intAttributes == nil {
		return e
	}
	e.intAttributes.Del("start")
	return e
}

// Kind of list marker.
func (e *OlElement) Type(c OlTypeChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("type", string(c))
	return e
}

type OlTypeChoice string

const (
	// Numbers (default)
	OlType1 OlTypeChoice = "1"
	// Lowercase letters
	OlTypeLowerA OlTypeChoice = "a"
	// Uppercase letters
	OlTypeUpperA OlTypeChoice = "A"
	// Lowercase roman numerals
	OlTypeLowerI OlTypeChoice = "i"
	// Uppercase roman numerals
	OlTypeUpperI OlTypeChoice = "I"
)

// Kind of list marker.
// Remove the attribute Type from the element.
func (e *OlElement) TypeRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("type")
	return e
}

// The accesskey global Attribute provides a hint for generating a keyboard
// shortcut for the current element. The attribute value must consist of a
// single printable character (which includes accented and other characters that
// can be generated by the keyboard).
func (e *OlElement) Accesskey(r rune) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("accesskey", string(r))
	return e
}

// The accesskey global Attribute provides a hint for generating a keyboard
// shortcut for the current element. The attribute value must consist of a
// single printable character (which includes accented and other characters that
// can be generated by the keyboard).
func (e *OlElement) IfAccesskey(condition bool, r rune) *OlElement {
	if condition {
		e.Accesskey(r)
	}
	return e
}

// The accesskey global Attribute provides a hint for generating a keyboard
// shortcut for the current element. The attribute value must consist of a
// single printable character (which includes accented and other characters that
// can be generated by the keyboard).
// Remove the attribute Accesskey from the element.
func (e *OlElement) AccesskeyRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("accesskey")
	return e
}

// The autocapitalize global Attribute is an enumerated attribute that controls
// whether and how text input is automatically capitalized as it is
// entered/edited by the user. autocapitalize can be set on <input> and
// <textarea> elements, and on their containing <form> elements. When
// autocapitalize is set on a <form> element, it sets the autocapitalize
// behavior for all contained <input>s and <textarea>s, overriding any
// autocapitalize values set on contained elements. autocapitalize has no effect
// on the url, email, or password <input> types, where autocapitalization is
// never enabled. Where autocapitalize is not specified, the adopted default
// behavior varies between browsers. For example: Chrome and Safari default to
// on/sentences Firefox defaults to off/none.
func (e *OlElement) Autocapitalize(c OlAutocapitalizeChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("autocapitalize", string(c))
	return e
}

type OlAutocapitalizeChoice string

const (
	// Do not automatically capitalize any text.
	OlAutocapitalizeOff OlAutocapitalizeChoice = "off"
	// Do not automatically capitalize any text.
	OlAutocapitalizeNone OlAutocapitalizeChoice = "none"
	// Automatically capitalize the first character of each sentence.
	OlAutocapitalizeSentences OlAutocapitalizeChoice = "sentences"
	// Automatically capitalize the first character of each sentence.
	OlAutocapitalizeOn OlAutocapitalizeChoice = "on"
	// Automatically capitalize the first character of each word.
	OlAutocapitalizeWords OlAutocapitalizeChoice = "words"
	// Automatically capitalize all characters.
	OlAutocapitalizeCharacters OlAutocapitalizeChoice = "characters"
)

// The autocapitalize global Attribute is an enumerated attribute that controls
// whether and how text input is automatically capitalized as it is
// entered/edited by the user. autocapitalize can be set on <input> and
// <textarea> elements, and on their containing <form> elements. When
// autocapitalize is set on a <form> element, it sets the autocapitalize
// behavior for all contained <input>s and <textarea>s, overriding any
// autocapitalize values set on contained elements. autocapitalize has no effect
// on the url, email, or password <input> types, where autocapitalization is
// never enabled. Where autocapitalize is not specified, the adopted default
// behavior varies between browsers. For example: Chrome and Safari default to
// on/sentences Firefox defaults to off/none.
// Remove the attribute Autocapitalize from the element.
func (e *OlElement) AutocapitalizeRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("autocapitalize")
	return e
}

// The autofocus global Attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// Attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *OlElement) Autofocus() *OlElement {
	e.AutofocusSet(true)
	return e
}

// The autofocus global Attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// Attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *OlElement) IfAutofocus(condition bool) *OlElement {
	if condition {
		e.AutofocusSet(true)
	}
	return e
}

// The autofocus global Attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// Attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
// Set the attribute Autofocus to the value b explicitly.
func (e *OlElement) AutofocusSet(b bool) *OlElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("autofocus", b)
	return e
}

// The autofocus global Attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// Attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *OlElement) IfSetAutofocus(condition bool, b bool) *OlElement {
	if condition {
		e.AutofocusSet(b)
	}
	return e
}

// Remove the attribute Autofocus from the element.
// The autofocus global Attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// Attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *OlElement) AutofocusRemove() *OlElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("autofocus")
	return e
}

// The class global Attribute is a space-separated list of the case-sensitive
// classes of the element. Classes allow CSS and JavaScript to select and access
// specific elements via the class selectors or functions like the DOM method
// document.getElementsByClassName.
func (e *OlElement) Class(s string) *OlElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// The class global Attribute is a space-separated list of the case-sensitive
// classes of the element. Classes allow CSS and JavaScript to select and access
// specific elements via the class selectors or functions like the DOM method
// document.getElementsByClassName.
func (e *OlElement) IfClass(condition bool, s string) *OlElement {
	if condition {
		e.Class(s)
	}
	return e
}

// The class global Attribute is a space-separated list of the case-sensitive
// classes of the element. Classes allow CSS and JavaScript to select and access
// specific elements via the class selectors or functions like the DOM method
// document.getElementsByClassName.
// Remove the values from the attribute Class in the element.
func (e *OlElement) ClassRemove(s ...string) *OlElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// The contenteditable global Attribute is an enumerated attribute indicating if
// the element should be editable by the user. If so, the browser modifies its
// widget to allow editing.
func (e *OlElement) Contenteditable(c OlContenteditableChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("contenteditable", string(c))
	return e
}

type OlContenteditableChoice string

const (
	// The element is editable.
	OlContenteditableEmpty OlContenteditableChoice = ""
	// The element is editable.
	OlContenteditableTrue OlContenteditableChoice = "true"
	// The element is not editable.
	OlContenteditableFalse OlContenteditableChoice = "false"
	// which indicates that the element's raw text is editable, but rich text
	// formatting is disabled.
	OlContenteditablePlaintextOnly OlContenteditableChoice = "plaintext-only"
)

// The contenteditable global Attribute is an enumerated attribute indicating if
// the element should be editable by the user. If so, the browser modifies its
// widget to allow editing.
// Remove the attribute Contenteditable from the element.
func (e *OlElement) ContenteditableRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("contenteditable")
	return e
}

// The dir global Attribute is an enumerated attribute that indicates the
// directionality of the element's text. Note: This attribute is mandatory for
// the <bdo> element where it has a different semantic meaning. This attribute
// is not inherited by the <bdi> element. If not set, its value is auto. This
// attribute can be overridden by the CSS properties direction and unicode-bidi,
// if a CSS page is active and the element supports these properties. As the
// directionality of the text is semantically related to its content and not to
// its presentation, it is recommended that web developers use this attribute
// instead of the related CSS properties when possible. That way, the text will
// display correctly even on a browser that doesn't support CSS or has the CSS
// deactivated. The auto value should be used for data with an unknown
// directionality, like data coming from user input, eventually stored in a
// database.
func (e *OlElement) Dir(c OlDirChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("dir", string(c))
	return e
}

type OlDirChoice string

const (
	// which means left to right and is to be used for languages that are written
	// from the left to the right (like English);
	OlDirLtr OlDirChoice = "ltr"
	// which means right to left and is to be used for languages that are written
	// from the right to the left (like Arabic);
	OlDirRtl OlDirChoice = "rtl"
	// which lets the user agent decide. It uses a basic algorithm as it parses the
	// characters inside the element until it finds a character with a strong
	// directionality, then it applies that directionality to the whole element.
	OlDirAuto OlDirChoice = "auto"
)

// The dir global Attribute is an enumerated attribute that indicates the
// directionality of the element's text. Note: This attribute is mandatory for
// the <bdo> element where it has a different semantic meaning. This attribute
// is not inherited by the <bdi> element. If not set, its value is auto. This
// attribute can be overridden by the CSS properties direction and unicode-bidi,
// if a CSS page is active and the element supports these properties. As the
// directionality of the text is semantically related to its content and not to
// its presentation, it is recommended that web developers use this attribute
// instead of the related CSS properties when possible. That way, the text will
// display correctly even on a browser that doesn't support CSS or has the CSS
// deactivated. The auto value should be used for data with an unknown
// directionality, like data coming from user input, eventually stored in a
// database.
// Remove the attribute Dir from the element.
func (e *OlElement) DirRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("dir")
	return e
}

// The draggable global Attribute is an enumerated attribute that indicates
// whether the element can be dragged, either with native browser behavior or
// the HTML Drag and Drop API.
func (e *OlElement) Draggable(c OlDraggableChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("draggable", string(c))
	return e
}

type OlDraggableChoice string

const (
	// The element is draggable.
	OlDraggableTrue OlDraggableChoice = "true"
	// The element is not draggable.
	OlDraggableFalse OlDraggableChoice = "false"
	// drag behavior is the default browser behavior: only text selections, images,
	// and links can be dragged. For other elements, the event ondragstart must be
	// set for drag and drop to work
	OlDraggableEmpty OlDraggableChoice = ""
	// drag behavior is the default browser behavior: only text selections, images,
	// and links can be dragged. For other elements, the event ondragstart must be
	// set for drag and drop to work
	OlDraggableAuto OlDraggableChoice = "auto"
)

// The draggable global Attribute is an enumerated attribute that indicates
// whether the element can be dragged, either with native browser behavior or
// the HTML Drag and Drop API.
// Remove the attribute Draggable from the element.
func (e *OlElement) DraggableRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("draggable")
	return e
}

// The enterkeyhint global Attribute is an enumerated attribute defining what
// action label (or icon) to present for the enter key on virtual keyboards.
func (e *OlElement) Enterkeyhint(c OlEnterkeyhintChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("enterkeyhint", string(c))
	return e
}

type OlEnterkeyhintChoice string

const (
	// Typically inserting a new line.
	OlEnterkeyhintEnter OlEnterkeyhintChoice = "enter"
	// Typically meaning there is nothing more to input and the input method editor
	// (IME) will be closed.
	OlEnterkeyhintDone OlEnterkeyhintChoice = "done"
	// Typically meaning to take the user to the target of the text they typed.
	OlEnterkeyhintGo OlEnterkeyhintChoice = "go"
	// Typically meaning to take the user to the next field that will accept text.
	OlEnterkeyhintNext OlEnterkeyhintChoice = "next"
	// Typically meaning to take the user to the previous field that will accept
	// text.
	OlEnterkeyhintPrevious OlEnterkeyhintChoice = "previous"
	// Typically taking the user to the results of searching for the text they have
	// typed.
	OlEnterkeyhintSearch OlEnterkeyhintChoice = "search"
	// Typically delivering the text to its target.
	OlEnterkeyhintSend OlEnterkeyhintChoice = "send"
)

// The enterkeyhint global Attribute is an enumerated attribute defining what
// action label (or icon) to present for the enter key on virtual keyboards.
// Remove the attribute Enterkeyhint from the element.
func (e *OlElement) EnterkeyhintRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("enterkeyhint")
	return e
}

// The exportparts global Attribute allows you to select and style elements
// existing in nested shadow trees, by exporting their part names. The shadow
// tree is an isolated structure where identifiers, classes, and styles cannot
// be reached by selectors or queries belonging to a regular DOM. To apply a
// style to an element living in a shadow tree, by CSS rule created outside of
// it, part global attribute has to be used. It has to be assigned to an element
// present in Shadow Tree, and its value should be some identifier. Rules
// present outside of the shadow tree, must use the ::part pseudo-element,
// containing the same identifier as the argument. The global attribute part
// makes the element visible on just a single level of depth. When the shadow
// tree is nested, parts will be visible only to the parent of the shadow tree
// but not to its ancestor. Exporting parts further down is exactly what
// exportparts attribute is for. Attribute exportparts must be placed on a
// shadow Host, which is the element to which the shadow tree is attached. The
// value of the attribute should be a comma-separated list of part names present
// in the shadow tree and which should be made available via a DOM outside of
// the current structure.
func (e *OlElement) Exportparts(s string) *OlElement {
	values := strings.Split(s, ",")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("exportparts")
	if !ok {
		ds = newDelimitedBuilder[string](",")
		e.delimitedStrings.Set("exportparts", ds)
	}
	ds.Add(values...)
	return e
}

// The exportparts global Attribute allows you to select and style elements
// existing in nested shadow trees, by exporting their part names. The shadow
// tree is an isolated structure where identifiers, classes, and styles cannot
// be reached by selectors or queries belonging to a regular DOM. To apply a
// style to an element living in a shadow tree, by CSS rule created outside of
// it, part global attribute has to be used. It has to be assigned to an element
// present in Shadow Tree, and its value should be some identifier. Rules
// present outside of the shadow tree, must use the ::part pseudo-element,
// containing the same identifier as the argument. The global attribute part
// makes the element visible on just a single level of depth. When the shadow
// tree is nested, parts will be visible only to the parent of the shadow tree
// but not to its ancestor. Exporting parts further down is exactly what
// exportparts attribute is for. Attribute exportparts must be placed on a
// shadow Host, which is the element to which the shadow tree is attached. The
// value of the attribute should be a comma-separated list of part names present
// in the shadow tree and which should be made available via a DOM outside of
// the current structure.
func (e *OlElement) IfExportparts(condition bool, s string) *OlElement {
	if condition {
		e.Exportparts(s)
	}
	return e
}

// The exportparts global Attribute allows you to select and style elements
// existing in nested shadow trees, by exporting their part names. The shadow
// tree is an isolated structure where identifiers, classes, and styles cannot
// be reached by selectors or queries belonging to a regular DOM. To apply a
// style to an element living in a shadow tree, by CSS rule created outside of
// it, part global attribute has to be used. It has to be assigned to an element
// present in Shadow Tree, and its value should be some identifier. Rules
// present outside of the shadow tree, must use the ::part pseudo-element,
// containing the same identifier as the argument. The global attribute part
// makes the element visible on just a single level of depth. When the shadow
// tree is nested, parts will be visible only to the parent of the shadow tree
// but not to its ancestor. Exporting parts further down is exactly what
// exportparts attribute is for. Attribute exportparts must be placed on a
// shadow Host, which is the element to which the shadow tree is attached. The
// value of the attribute should be a comma-separated list of part names present
// in the shadow tree and which should be made available via a DOM outside of
// the current structure.
// Remove the values from the attribute Exportparts in the element.
func (e *OlElement) ExportpartsRemove(s ...string) *OlElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("exportparts")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// The hidden global Attribute is a Boolean attribute indicating that the
// element is not yet, or is no longer, relevant. For example, it can be used to
// hide elements of the page that can't be used until the login process has been
// completed. Note that browsers typically implement hidden until found using
// content-visibility: hidden. This means that unlike elements in the hidden
// state, elements in the hidden until found state will have generated boxes,
// meaning that: the element will participate in page layout margin, borders,
// padding, and background for the element will be rendered. Also, the element
// needs to be affected by layout containment in order to be revealed. This
// means that if the element in the hidden until found state has a display value
// of none, contents, or inline, then the element will not be revealed by find
// in page or fragment navigation.
func (e *OlElement) Hidden(c OlHiddenChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("hidden", string(c))
	return e
}

type OlHiddenChoice string

const (
	// set the element to the hidden state. Additionally, invalid values set the
	// element to the hidden state.
	OlHiddenEmpty OlHiddenChoice = ""
	// set the element to the hidden state. Additionally, invalid values set the
	// element to the hidden state.
	OlHiddenHidden OlHiddenChoice = "hidden"
	// the element is hidden but its content will be accessible to the browser's
	// "find in page" feature or to fragment navigation. When these features cause a
	// scroll to an element in a hidden until found subtree, the browser will fire a
	// beforematch event on the hidden element remove the hidden attribute from the
	// element scroll to the element
	//
	OlHiddenUntilFound OlHiddenChoice = "until-found"
)

// The hidden global Attribute is a Boolean attribute indicating that the
// element is not yet, or is no longer, relevant. For example, it can be used to
// hide elements of the page that can't be used until the login process has been
// completed. Note that browsers typically implement hidden until found using
// content-visibility: hidden. This means that unlike elements in the hidden
// state, elements in the hidden until found state will have generated boxes,
// meaning that: the element will participate in page layout margin, borders,
// padding, and background for the element will be rendered. Also, the element
// needs to be affected by layout containment in order to be revealed. This
// means that if the element in the hidden until found state has a display value
// of none, contents, or inline, then the element will not be revealed by find
// in page or fragment navigation.
// Remove the attribute Hidden from the element.
func (e *OlElement) HiddenRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("hidden")
	return e
}

// The id global Attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *OlElement) ID(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("id", s)
	return e
}

// The id global Attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *OlElement) IDf(format string, args ...any) *OlElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// The id global Attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *OlElement) IfID(condition bool, s string) *OlElement {
	if condition {
		e.ID(s)
	}
	return e
}

// The id global Attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *OlElement) IfIDf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// The id global Attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
// Remove the attribute ID from the element.
func (e *OlElement) IDRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("id")
	return e
}

// The inert global Attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *OlElement) Inert() *OlElement {
	e.InertSet(true)
	return e
}

// The inert global Attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *OlElement) IfInert(condition bool) *OlElement {
	if condition {
		e.InertSet(true)
	}
	return e
}

// The inert global Attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
// Set the attribute Inert to the value b explicitly.
func (e *OlElement) InertSet(b bool) *OlElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("inert", b)
	return e
}

// The inert global Attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *OlElement) IfSetInert(condition bool, b bool) *OlElement {
	if condition {
		e.InertSet(b)
	}
	return e
}

// Remove the attribute Inert from the element.
// The inert global Attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *OlElement) InertRemove() *OlElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("inert")
	return e
}

// The inputmode global Attribute is an enumerated attribute that hints at the
// type of data that might be entered by the user while editing the element or
// its contents. This allows a browser to display an appropriate virtual
// keyboard. It is used primarily on <input> elements, but is usable on any
// element in contenteditable mode. It's important to understand that the
// inputmode attribute doesn't cause any validity requirements to be enforced on
// input. To require that input conforms to a particular data type, choose an
// appropriate <input> element type. For specific guidance on choosing <input>
// types, see the Values section.
func (e *OlElement) Inputmode(c OlInputmodeChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("inputmode", string(c))
	return e
}

type OlInputmodeChoice string

const (
	// No virtual keyboard. For when the page implements its own keyboard input
	// control.
	OlInputmodeNone OlInputmodeChoice = "none"
	// Standard input keyboard for the user's current locale.
	OlInputmodeEmpty OlInputmodeChoice = ""
	// Standard input keyboard for the user's current locale.
	OlInputmodeText OlInputmodeChoice = "text"
	// Fractional numeric input keyboard containing the digits and decimal separator
	// for the user's locale (typically . or ,). Devices may or may not show a minus
	// key (-).
	OlInputmodeDecimal OlInputmodeChoice = "decimal"
	// Numeric input keyboard, but only requires the digits 0–9. Devices may or
	// may not show a minus key.
	OlInputmodeNumeric OlInputmodeChoice = "numeric"
	// A telephone keypad input, including the digits 0–9, the asterisk (*), and
	// the pound (#) key. Inputs that *require* a telephone number should typically
	// use <input type="tel"> instead.
	OlInputmodeTel OlInputmodeChoice = "tel"
	// A virtual keyboard optimized for search input. For instance, the
	// return/submit key may be labeled "Search", along with possible other
	// optimizations. Inputs that require a search query should typically use <input
	// type="search"> instead.
	OlInputmodeSearch OlInputmodeChoice = "search"
	// A virtual keyboard optimized for entering email addresses. Typically includes
	// the @character as well as other optimizations. Inputs that require email
	// addresses should typically use <input type="email"> instead.
	OlInputmodeEmail OlInputmodeChoice = "email"
	// A keypad optimized for entering URLs. This may have the / key more prominent,
	// for example. Enhanced features could include history access and so on. Inputs
	// that require a URL should typically use <input type="url"> instead.
	OlInputmodeURL OlInputmodeChoice = "url"
)

// The inputmode global Attribute is an enumerated attribute that hints at the
// type of data that might be entered by the user while editing the element or
// its contents. This allows a browser to display an appropriate virtual
// keyboard. It is used primarily on <input> elements, but is usable on any
// element in contenteditable mode. It's important to understand that the
// inputmode attribute doesn't cause any validity requirements to be enforced on
// input. To require that input conforms to a particular data type, choose an
// appropriate <input> element type. For specific guidance on choosing <input>
// types, see the Values section.
// Remove the attribute Inputmode from the element.
func (e *OlElement) InputmodeRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("inputmode")
	return e
}

// The is global Attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *OlElement) Is(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("is", s)
	return e
}

// The is global Attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *OlElement) Isf(format string, args ...any) *OlElement {
	return e.Is(fmt.Sprintf(format, args...))
}

// The is global Attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *OlElement) IfIs(condition bool, s string) *OlElement {
	if condition {
		e.Is(s)
	}
	return e
}

// The is global Attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *OlElement) IfIsf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Is(fmt.Sprintf(format, args...))
	}
	return e
}

// The is global Attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
// Remove the attribute Is from the element.
func (e *OlElement) IsRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("is")
	return e
}

// The itemid global Attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid Attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *OlElement) Itemid(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemid", s)
	return e
}

// The itemid global Attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid Attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *OlElement) Itemidf(format string, args ...any) *OlElement {
	return e.Itemid(fmt.Sprintf(format, args...))
}

// The itemid global Attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid Attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *OlElement) IfItemid(condition bool, s string) *OlElement {
	if condition {
		e.Itemid(s)
	}
	return e
}

// The itemid global Attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid Attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *OlElement) IfItemidf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Itemid(fmt.Sprintf(format, args...))
	}
	return e
}

// The itemid global Attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid Attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
// Remove the attribute Itemid from the element.
func (e *OlElement) ItemidRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemid")
	return e
}

// The itemprop global Attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *OlElement) Itemprop(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemprop", s)
	return e
}

// The itemprop global Attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *OlElement) Itempropf(format string, args ...any) *OlElement {
	return e.Itemprop(fmt.Sprintf(format, args...))
}

// The itemprop global Attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *OlElement) IfItemprop(condition bool, s string) *OlElement {
	if condition {
		e.Itemprop(s)
	}
	return e
}

// The itemprop global Attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *OlElement) IfItempropf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Itemprop(fmt.Sprintf(format, args...))
	}
	return e
}

// The itemprop global Attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
// Remove the attribute Itemprop from the element.
func (e *OlElement) ItempropRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemprop")
	return e
}

// Properties that are not descendants of an element with the itemscope
// Attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *OlElement) Itemref(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemref", s)
	return e
}

// Properties that are not descendants of an element with the itemscope
// Attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *OlElement) Itemreff(format string, args ...any) *OlElement {
	return e.Itemref(fmt.Sprintf(format, args...))
}

// Properties that are not descendants of an element with the itemscope
// Attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *OlElement) IfItemref(condition bool, s string) *OlElement {
	if condition {
		e.Itemref(s)
	}
	return e
}

// Properties that are not descendants of an element with the itemscope
// Attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *OlElement) IfItemreff(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Itemref(fmt.Sprintf(format, args...))
	}
	return e
}

// Properties that are not descendants of an element with the itemscope
// Attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
// Remove the attribute Itemref from the element.
func (e *OlElement) ItemrefRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemref")
	return e
}

// The itemscope global Attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *OlElement) Itemscope() *OlElement {
	e.ItemscopeSet(true)
	return e
}

// The itemscope global Attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *OlElement) IfItemscope(condition bool) *OlElement {
	if condition {
		e.ItemscopeSet(true)
	}
	return e
}

// The itemscope global Attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
// Set the attribute Itemscope to the value b explicitly.
func (e *OlElement) ItemscopeSet(b bool) *OlElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("itemscope", b)
	return e
}

// The itemscope global Attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *OlElement) IfSetItemscope(condition bool, b bool) *OlElement {
	if condition {
		e.ItemscopeSet(b)
	}
	return e
}

// Remove the attribute Itemscope from the element.
// The itemscope global Attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *OlElement) ItemscopeRemove() *OlElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("itemscope")
	return e
}

// The itemtype global Attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *OlElement) Itemtype(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemtype", s)
	return e
}

// The itemtype global Attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *OlElement) Itemtypef(format string, args ...any) *OlElement {
	return e.Itemtype(fmt.Sprintf(format, args...))
}

// The itemtype global Attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *OlElement) IfItemtype(condition bool, s string) *OlElement {
	if condition {
		e.Itemtype(s)
	}
	return e
}

// The itemtype global Attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *OlElement) IfItemtypef(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Itemtype(fmt.Sprintf(format, args...))
	}
	return e
}

// The itemtype global Attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
// Remove the attribute Itemtype from the element.
func (e *OlElement) ItemtypeRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemtype")
	return e
}

// The lang global Attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *OlElement) Lang(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("lang", s)
	return e
}

// The lang global Attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *OlElement) Langf(format string, args ...any) *OlElement {
	return e.Lang(fmt.Sprintf(format, args...))
}

// The lang global Attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *OlElement) IfLang(condition bool, s string) *OlElement {
	if condition {
		e.Lang(s)
	}
	return e
}

// The lang global Attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *OlElement) IfLangf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Lang(fmt.Sprintf(format, args...))
	}
	return e
}

// The lang global Attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
// Remove the attribute Lang from the element.
func (e *OlElement) LangRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("lang")
	return e
}

// The nonce global Attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *OlElement) Nonce(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("nonce", s)
	return e
}

// The nonce global Attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *OlElement) Noncef(format string, args ...any) *OlElement {
	return e.Nonce(fmt.Sprintf(format, args...))
}

// The nonce global Attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *OlElement) IfNonce(condition bool, s string) *OlElement {
	if condition {
		e.Nonce(s)
	}
	return e
}

// The nonce global Attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *OlElement) IfNoncef(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Nonce(fmt.Sprintf(format, args...))
	}
	return e
}

// The nonce global Attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
// Remove the attribute Nonce from the element.
func (e *OlElement) NonceRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("nonce")
	return e
}

// The part global Attribute contains a space-separated list of the part names
// of the element. Part names allows CSS to select and style specific elements
// in a shadow tree via the ::part pseudo-element.
func (e *OlElement) Part(s string) *OlElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("part")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("part", ds)
	}
	ds.Add(values...)
	return e
}

// The part global Attribute contains a space-separated list of the part names
// of the element. Part names allows CSS to select and style specific elements
// in a shadow tree via the ::part pseudo-element.
func (e *OlElement) IfPart(condition bool, s string) *OlElement {
	if condition {
		e.Part(s)
	}
	return e
}

// The part global Attribute contains a space-separated list of the part names
// of the element. Part names allows CSS to select and style specific elements
// in a shadow tree via the ::part pseudo-element.
// Remove the values from the attribute Part in the element.
func (e *OlElement) PartRemove(s ...string) *OlElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("part")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// The popover global Attribute is used to designate an element as a popover
// element. Popover elements are hidden via display: none until opened via an
// invoking/control element (i.e. a <button> or <input type="button"> with a
// popovertarget attribute) or a HTMLElement.showPopover() call. When open,
// popover elements will appear above all other elements in the top layer, and
// won't be influenced by parent elements' position or overflow styling.
func (e *OlElement) Popover(c OlPopoverChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("popover", string(c))
	return e
}

type OlPopoverChoice string

const (
	// Popovers that have the auto state can be "light dismissed" by selecting
	// outside the popover area, and generally only allow one popover to be
	// displayed on-screen at a time.
	OlPopoverAuto OlPopoverChoice = "auto"
	// Popovers that have the auto state can be "light dismissed" by selecting
	// outside the popover area, and generally only allow one popover to be
	// displayed on-screen at a time.
	OlPopoverEmpty OlPopoverChoice = ""
	// manual popovers must always be explicitly hidden, but allow for use cases
	// such as nested popovers in menus.
	OlPopoverManual OlPopoverChoice = "manual"
)

// The popover global Attribute is used to designate an element as a popover
// element. Popover elements are hidden via display: none until opened via an
// invoking/control element (i.e. a <button> or <input type="button"> with a
// popovertarget attribute) or a HTMLElement.showPopover() call. When open,
// popover elements will appear above all other elements in the top layer, and
// won't be influenced by parent elements' position or overflow styling.
// Remove the attribute Popover from the element.
func (e *OlElement) PopoverRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("popover")
	return e
}

// The role global Attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *OlElement) Role(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("role", s)
	return e
}

// The role global Attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *OlElement) Rolef(format string, args ...any) *OlElement {
	return e.Role(fmt.Sprintf(format, args...))
}

// The role global Attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *OlElement) IfRole(condition bool, s string) *OlElement {
	if condition {
		e.Role(s)
	}
	return e
}

// The role global Attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *OlElement) IfRolef(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Role(fmt.Sprintf(format, args...))
	}
	return e
}

// The role global Attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
// Remove the attribute Role from the element.
func (e *OlElement) RoleRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("role")
	return e
}

// The slot global Attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *OlElement) Slot(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("slot", s)
	return e
}

// The slot global Attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *OlElement) Slotf(format string, args ...any) *OlElement {
	return e.Slot(fmt.Sprintf(format, args...))
}

// The slot global Attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *OlElement) IfSlot(condition bool, s string) *OlElement {
	if condition {
		e.Slot(s)
	}
	return e
}

// The slot global Attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *OlElement) IfSlotf(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Slot(fmt.Sprintf(format, args...))
	}
	return e
}

// The slot global Attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
// Remove the attribute Slot from the element.
func (e *OlElement) SlotRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("slot")
	return e
}

// The spellcheck global Attribute is an enumerated attribute that defines
// whether the element may be checked for spelling errors. If this attribute is
// not set, its default value is element-type and browser-defined. This default
// value may also be inherited, which means that the element content will be
// checked for spelling errors only if its nearest ancestor has a spellcheck
// state of true. Security and privacy concerns Using spellchecking can have
// consequences for users' security and privacy. The specification does not
// regulate how spellchecking is done and the content of the element may be sent
// to a third party for spellchecking results (see enhanced spellchecking and
// "spell-jacking"). You should consider setting spellcheck to false for
// elements that can contain sensitive information.
func (e *OlElement) Spellcheck(c OlSpellcheckChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("spellcheck", string(c))
	return e
}

type OlSpellcheckChoice string

const (
	// The element will be checked for spelling errors.
	OlSpellcheckEmpty OlSpellcheckChoice = ""
	// The element will be checked for spelling errors.
	OlSpellcheckTrue OlSpellcheckChoice = "true"
	// The element will not be checked for spelling errors.
	OlSpellcheckFalse OlSpellcheckChoice = "false"
)

// The spellcheck global Attribute is an enumerated attribute that defines
// whether the element may be checked for spelling errors. If this attribute is
// not set, its default value is element-type and browser-defined. This default
// value may also be inherited, which means that the element content will be
// checked for spelling errors only if its nearest ancestor has a spellcheck
// state of true. Security and privacy concerns Using spellchecking can have
// consequences for users' security and privacy. The specification does not
// regulate how spellchecking is done and the content of the element may be sent
// to a third party for spellchecking results (see enhanced spellchecking and
// "spell-jacking"). You should consider setting spellcheck to false for
// elements that can contain sensitive information.
// Remove the attribute Spellcheck from the element.
func (e *OlElement) SpellcheckRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("spellcheck")
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) StylePairs(pairs ...string) *OlElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv = newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) Style(s string) *OlElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) IfStyle(condition bool, s string) *OlElement {
	if condition {
		e.Style(s)
	}
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) StyleAdd(k string, v string) *OlElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) StyleAddf(k string, format string, args ...any) *OlElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) IfStyleAdd(condition bool, k string, v string) *OlElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *OlElement) IfStyleAddf(condition bool, k string, format string, args ...any) *OlElement {
	if condition {
		e.StyleAddf(k, format, args...)
	}
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
// Add the attributes in the map to the element.
func (e *OlElement) StyleMap(m map[string]string) *OlElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// The style global Attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
// Remove the attribute Style from the element.
func (e *OlElement) StyleRemove(keys ...string) *OlElement {
	if e.keyValueStrings == nil {
		return e
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}

// The tabindex global Attribute indicates if its element can be focused, and
// if/where it participates in sequential keyboard navigation (usually with the
// Tab key, hence the name). It accepts an integer as a value, with different
// results depending on the integer's value: a negative value (usually
// tabindex="-1") means that the element should be focusable, but should not be
// reachable via sequential keyboard navigation; a value of 0 (tabindex="0")
// means that the element should be focusable and reachable via sequential
// keyboard navigation, but its relative order is defined by the platform
// convention; a positive value means should be focusable and reachable via
// sequential keyboard navigation; its relative order is defined by the value of
// the attribute: the sequential follow the increasing number of the tabindex.
// If several elements share the same tabindex, their relative order follows
// their relative position in the document.
func (e *OlElement) Tabindex(i int) *OlElement {
	if e.intAttributes == nil {
		e.intAttributes = treemap.New[string, int]()
	}
	e.intAttributes.Set("tabindex", i)
	return e
}

// The tabindex global Attribute indicates if its element can be focused, and
// if/where it participates in sequential keyboard navigation (usually with the
// Tab key, hence the name). It accepts an integer as a value, with different
// results depending on the integer's value: a negative value (usually
// tabindex="-1") means that the element should be focusable, but should not be
// reachable via sequential keyboard navigation; a value of 0 (tabindex="0")
// means that the element should be focusable and reachable via sequential
// keyboard navigation, but its relative order is defined by the platform
// convention; a positive value means should be focusable and reachable via
// sequential keyboard navigation; its relative order is defined by the value of
// the attribute: the sequential follow the increasing number of the tabindex.
// If several elements share the same tabindex, their relative order follows
// their relative position in the document.
func (e *OlElement) IfTabindex(condition bool, i int) *OlElement {
	if condition {
		e.Tabindex(i)
	}
	return e
}

// The tabindex global Attribute indicates if its element can be focused, and
// if/where it participates in sequential keyboard navigation (usually with the
// Tab key, hence the name). It accepts an integer as a value, with different
// results depending on the integer's value: a negative value (usually
// tabindex="-1") means that the element should be focusable, but should not be
// reachable via sequential keyboard navigation; a value of 0 (tabindex="0")
// means that the element should be focusable and reachable via sequential
// keyboard navigation, but its relative order is defined by the platform
// convention; a positive value means should be focusable and reachable via
// sequential keyboard navigation; its relative order is defined by the value of
// the attribute: the sequential follow the increasing number of the tabindex.
// If several elements share the same tabindex, their relative order follows
// their relative position in the document.
// Remove the attribute Tabindex from the element.
func (e *OlElement) TabindexRemove() *OlElement {
	if e.intAttributes == nil {
		return e
	}
	e.intAttributes.Del("tabindex")
	return e
}

// The title global Attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *OlElement) Title(s string) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("title", s)
	return e
}

// The title global Attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *OlElement) Titlef(format string, args ...any) *OlElement {
	return e.Title(fmt.Sprintf(format, args...))
}

// The title global Attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *OlElement) IfTitle(condition bool, s string) *OlElement {
	if condition {
		e.Title(s)
	}
	return e
}

// The title global Attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *OlElement) IfTitlef(condition bool, format string, args ...any) *OlElement {
	if condition {
		e.Title(fmt.Sprintf(format, args...))
	}
	return e
}

// The title global Attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
// Remove the attribute Title from the element.
func (e *OlElement) TitleRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("title")
	return e
}

// The translate global Attribute is an enumerated attribute that is used to
// specify whether an element's attribute values and the values of its Text node
// children are to be translated when the page is localized, or whether to leave
// them unchanged.
func (e *OlElement) Translate(c OlTranslateChoice) *OlElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("translate", string(c))
	return e
}

type OlTranslateChoice string

const (
	// indicates that the element should be translated when the page is localized.
	OlTranslateEmpty OlTranslateChoice = ""
	// indicates that the element should be translated when the page is localized.
	OlTranslateYes OlTranslateChoice = "yes"
	// indicates that the element must not be translated when the page is localized.
	OlTranslateNo OlTranslateChoice = "no"
)

// The translate global Attribute is an enumerated attribute that is used to
// specify whether an element's attribute values and the values of its Text node
// children are to be translated when the page is localized, or whether to leave
// them unchanged.
// Remove the attribute Translate from the element.
func (e *OlElement) TranslateRemove() *OlElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("translate")
	return e
}
