// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements html wbr is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The HTML <wbr> element represents a word break opportunity—a position
// within text where the browser may optionally break a line, though its
// line-breaking rules would not otherwise create a break at that location.
type WbrElement struct {
	*Element
}

// Create a new WbrElement element. This will create a new element
// with the tag "wbr" during rendering.
func Wbr() *WbrElement {
	e := NewElement("wbr")
	e.isSelfClosing = true

	return &WbrElement{Element: e}
}

func (e *WbrElement) Children(children ...ElementRenderer) *WbrElement {
	e.descendants = append(e.descendants, children...)
	return e
}

func (e *WbrElement) IfChildren(condition bool, children ...ElementRenderer) *WbrElement {
	if condition {
		e.descendants = append(e.descendants, children...)
	}
	return e
}

func (e *WbrElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *WbrElement {
	if condition {
		e.descendants = append(e.descendants, trueChildren)
	} else {
		e.descendants = append(e.descendants, falseChildren)
	}
	return e
}

func (e *WbrElement) BoolAttr(name string) *WbrElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set(name, true)
	return e
}

func (e *WbrElement) IfBoolAttr(condition bool, name string) *WbrElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *WbrElement) Attr(name, value string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set(name, value)
	return e
}

func (e *WbrElement) IfAttr(condition bool, name, value string) *WbrElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *WbrElement) Text(text string) *WbrElement {
	e.descendants = append(e.descendants, Text(text))
	return e
}

func (e *WbrElement) TextF(format string, args ...any) *WbrElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *WbrElement) IfText(condition bool, text string) *WbrElement {
	if condition {
		e.descendants = append(e.descendants, Text(text))
	}
	return e
}

func (e *WbrElement) IfTextF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.descendants = append(e.descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *WbrElement) Escaped(text string) *WbrElement {
	e.descendants = append(e.descendants, Escaped(text))
	return e
}

func (e *WbrElement) IfEscaped(condition bool, text string) *WbrElement {
	if condition {
		e.descendants = append(e.descendants, Escaped(text))
	}
	return e
}

func (e *WbrElement) EscapedF(format string, args ...any) *WbrElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *WbrElement) IfEscapedF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.descendants = append(e.descendants, EscapedF(format, args...))
	}
	return e
}

// The accesskey global attribute provides a hint for generating a keyboard
// shortcut for the current element. The attribute value must consist of a
// single printable character (which includes accented and other characters that
// can be generated by the keyboard).
func (e *WbrElement) Accesskey(r rune) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("accesskey", string(r))
	return e
}

// The accesskey global attribute provides a hint for generating a keyboard
// shortcut for the current element. The attribute value must consist of a
// single printable character (which includes accented and other characters that
// can be generated by the keyboard).
func (e *WbrElement) IfAccesskey(condition bool, r rune) *WbrElement {
	if condition {
		e.Accesskey(r)
	}
	return e
}

// The accesskey global attribute provides a hint for generating a keyboard
// shortcut for the current element. The attribute value must consist of a
// single printable character (which includes accented and other characters that
// can be generated by the keyboard).
// Remove the attribute Accesskey from the element.
func (e *WbrElement) AccesskeyRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("accesskey")
	return e
}

// The autocapitalize global attribute is an enumerated attribute that controls
// whether and how text input is automatically capitalized as it is
// entered/edited by the user. autocapitalize can be set on <input> and
// <textarea> elements, and on their containing <form> elements. When
// autocapitalize is set on a <form> element, it sets the autocapitalize
// behavior for all contained <input>s and <textarea>s, overriding any
// autocapitalize values set on contained elements. autocapitalize has no effect
// on the url, email, or password <input> types, where autocapitalization is
// never enabled. Where autocapitalize is not specified, the adopted default
// behavior varies between browsers. For example: Chrome and Safari default to
// on/sentences Firefox defaults to off/none.
func (e *WbrElement) Autocapitalize(c WbrAutocapitalizeChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("autocapitalize", string(c))
	return e
}

type WbrAutocapitalizeChoice string

const (
	// Do not automatically capitalize any text.
	WbrAutocapitalizeOff WbrAutocapitalizeChoice = "off"
	// Do not automatically capitalize any text.
	WbrAutocapitalizeNone WbrAutocapitalizeChoice = "none"
	// Automatically capitalize the first character of each sentence.
	WbrAutocapitalizeSentences WbrAutocapitalizeChoice = "sentences"
	// Automatically capitalize the first character of each sentence.
	WbrAutocapitalizeOn WbrAutocapitalizeChoice = "on"
	// Automatically capitalize the first character of each word.
	WbrAutocapitalizeWords WbrAutocapitalizeChoice = "words"
	// Automatically capitalize all characters.
	WbrAutocapitalizeCharacters WbrAutocapitalizeChoice = "characters"
)

// The autocapitalize global attribute is an enumerated attribute that controls
// whether and how text input is automatically capitalized as it is
// entered/edited by the user. autocapitalize can be set on <input> and
// <textarea> elements, and on their containing <form> elements. When
// autocapitalize is set on a <form> element, it sets the autocapitalize
// behavior for all contained <input>s and <textarea>s, overriding any
// autocapitalize values set on contained elements. autocapitalize has no effect
// on the url, email, or password <input> types, where autocapitalization is
// never enabled. Where autocapitalize is not specified, the adopted default
// behavior varies between browsers. For example: Chrome and Safari default to
// on/sentences Firefox defaults to off/none.
// Remove the attribute Autocapitalize from the element.
func (e *WbrElement) AutocapitalizeRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("autocapitalize")
	return e
}

// The autofocus global attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *WbrElement) Autofocus() *WbrElement {
	e.AutofocusSet(true)
	return e
}

// The autofocus global attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *WbrElement) IfAutofocus(condition bool) *WbrElement {
	if condition {
		e.AutofocusSet(true)
	}
	return e
}

// The autofocus global attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
// Set the attribute Autofocus to the value b explicitly.
func (e *WbrElement) AutofocusSet(b bool) *WbrElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("autofocus", b)
	return e
}

// The autofocus global attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *WbrElement) IfSetAutofocus(condition bool, b bool) *WbrElement {
	if condition {
		e.AutofocusSet(b)
	}
	return e
}

// Remove the attribute Autofocus from the element.
// The autofocus global attribute is a Boolean attribute indicating that an
// element should be focused on page load, or when the <dialog> that it is part
// of is displayed.
// Accessibility concerns Automatically focusing a form control can confuse
// visually-impaired people using screen-reading technology and people with
// cognitive impairments. When autofocus is assigned, screen-readers "teleport"
// their user to the form control without warning them beforehand.
// Use careful consideration for accessibility when applying the autofocus
// attribute. Automatically focusing on a control can cause the page to scroll
// on load. The focus can also cause dynamic keyboards to display on some touch
// devices. While a screen reader will announce the label of the form control
// receiving focus, the screen reader will not announce anything before the
// label, and the sighted user on a small device will equally miss the context
// created by the preceding content.
func (e *WbrElement) AutofocusRemove() *WbrElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("autofocus")
	return e
}

// The class global attribute is a space-separated list of the case-sensitive
// classes of the element. Classes allow CSS and JavaScript to select and access
// specific elements via the class selectors or functions like the DOM method
// document.getElementsByClassName.
func (e *WbrElement) Class(s string) *WbrElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// The class global attribute is a space-separated list of the case-sensitive
// classes of the element. Classes allow CSS and JavaScript to select and access
// specific elements via the class selectors or functions like the DOM method
// document.getElementsByClassName.
func (e *WbrElement) IfClass(condition bool, s string) *WbrElement {
	if condition {
		e.Class(s)
	}
	return e
}

// The class global attribute is a space-separated list of the case-sensitive
// classes of the element. Classes allow CSS and JavaScript to select and access
// specific elements via the class selectors or functions like the DOM method
// document.getElementsByClassName.
// Remove the values from the attribute Class in the element.
func (e *WbrElement) ClassRemove(s ...string) *WbrElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// The contenteditable global attribute is an enumerated attribute indicating if
// the element should be editable by the user. If so, the browser modifies its
// widget to allow editing.
func (e *WbrElement) Contenteditable(c WbrContenteditableChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("contenteditable", string(c))
	return e
}

type WbrContenteditableChoice string

const (
	// The element is editable.
	WbrContenteditableEmpty WbrContenteditableChoice = ""
	// The element is editable.
	WbrContenteditableTrue WbrContenteditableChoice = "true"
	// The element is not editable.
	WbrContenteditableFalse WbrContenteditableChoice = "false"
	// which indicates that the element's raw text is editable, but rich text
	// formatting is disabled.
	WbrContenteditablePlaintextOnly WbrContenteditableChoice = "plaintext-only"
)

// The contenteditable global attribute is an enumerated attribute indicating if
// the element should be editable by the user. If so, the browser modifies its
// widget to allow editing.
// Remove the attribute Contenteditable from the element.
func (e *WbrElement) ContenteditableRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("contenteditable")
	return e
}

// The dir global attribute is an enumerated attribute that indicates the
// directionality of the element's text. Note: This attribute is mandatory for
// the <bdo> element where it has a different semantic meaning. This attribute
// is not inherited by the <bdi> element. If not set, its value is auto. This
// attribute can be overridden by the CSS properties direction and unicode-bidi,
// if a CSS page is active and the element supports these properties. As the
// directionality of the text is semantically related to its content and not to
// its presentation, it is recommended that web developers use this attribute
// instead of the related CSS properties when possible. That way, the text will
// display correctly even on a browser that doesn't support CSS or has the CSS
// deactivated. The auto value should be used for data with an unknown
// directionality, like data coming from user input, eventually stored in a
// database.
func (e *WbrElement) Dir(c WbrDirChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("dir", string(c))
	return e
}

type WbrDirChoice string

const (
	// which means left to right and is to be used for languages that are written
	// from the left to the right (like English);
	WbrDirLtr WbrDirChoice = "ltr"
	// which means right to left and is to be used for languages that are written
	// from the right to the left (like Arabic);
	WbrDirRtl WbrDirChoice = "rtl"
	// which lets the user agent decide. It uses a basic algorithm as it parses the
	// characters inside the element until it finds a character with a strong
	// directionality, then it applies that directionality to the whole element.
	WbrDirAuto WbrDirChoice = "auto"
)

// The dir global attribute is an enumerated attribute that indicates the
// directionality of the element's text. Note: This attribute is mandatory for
// the <bdo> element where it has a different semantic meaning. This attribute
// is not inherited by the <bdi> element. If not set, its value is auto. This
// attribute can be overridden by the CSS properties direction and unicode-bidi,
// if a CSS page is active and the element supports these properties. As the
// directionality of the text is semantically related to its content and not to
// its presentation, it is recommended that web developers use this attribute
// instead of the related CSS properties when possible. That way, the text will
// display correctly even on a browser that doesn't support CSS or has the CSS
// deactivated. The auto value should be used for data with an unknown
// directionality, like data coming from user input, eventually stored in a
// database.
// Remove the attribute Dir from the element.
func (e *WbrElement) DirRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("dir")
	return e
}

// The draggable global attribute is an enumerated attribute that indicates
// whether the element can be dragged, either with native browser behavior or
// the HTML Drag and Drop API.
func (e *WbrElement) Draggable(c WbrDraggableChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("draggable", string(c))
	return e
}

type WbrDraggableChoice string

const (
	// The element is draggable.
	WbrDraggableTrue WbrDraggableChoice = "true"
	// The element is not draggable.
	WbrDraggableFalse WbrDraggableChoice = "false"
	// drag behavior is the default browser behavior: only text selections, images,
	// and links can be dragged. For other elements, the event ondragstart must be
	// set for drag and drop to work
	WbrDraggableEmpty WbrDraggableChoice = ""
	// drag behavior is the default browser behavior: only text selections, images,
	// and links can be dragged. For other elements, the event ondragstart must be
	// set for drag and drop to work
	WbrDraggableAuto WbrDraggableChoice = "auto"
)

// The draggable global attribute is an enumerated attribute that indicates
// whether the element can be dragged, either with native browser behavior or
// the HTML Drag and Drop API.
// Remove the attribute Draggable from the element.
func (e *WbrElement) DraggableRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("draggable")
	return e
}

// The enterkeyhint global attribute is an enumerated attribute defining what
// action label (or icon) to present for the enter key on virtual keyboards.
func (e *WbrElement) Enterkeyhint(c WbrEnterkeyhintChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("enterkeyhint", string(c))
	return e
}

type WbrEnterkeyhintChoice string

const (
	// Typically inserting a new line.
	WbrEnterkeyhintEnter WbrEnterkeyhintChoice = "enter"
	// Typically meaning there is nothing more to input and the input method editor
	// (IME) will be closed.
	WbrEnterkeyhintDone WbrEnterkeyhintChoice = "done"
	// Typically meaning to take the user to the target of the text they typed.
	WbrEnterkeyhintGo WbrEnterkeyhintChoice = "go"
	// Typically meaning to take the user to the next field that will accept text.
	WbrEnterkeyhintNext WbrEnterkeyhintChoice = "next"
	// Typically meaning to take the user to the previous field that will accept
	// text.
	WbrEnterkeyhintPrevious WbrEnterkeyhintChoice = "previous"
	// Typically taking the user to the results of searching for the text they have
	// typed.
	WbrEnterkeyhintSearch WbrEnterkeyhintChoice = "search"
	// Typically delivering the text to its target.
	WbrEnterkeyhintSend WbrEnterkeyhintChoice = "send"
)

// The enterkeyhint global attribute is an enumerated attribute defining what
// action label (or icon) to present for the enter key on virtual keyboards.
// Remove the attribute Enterkeyhint from the element.
func (e *WbrElement) EnterkeyhintRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("enterkeyhint")
	return e
}

// The exportparts global attribute allows you to select and style elements
// existing in nested shadow trees, by exporting their part names. The shadow
// tree is an isolated structure where identifiers, classes, and styles cannot
// be reached by selectors or queries belonging to a regular DOM. To apply a
// style to an element living in a shadow tree, by CSS rule created outside of
// it, part global attribute has to be used. It has to be assigned to an element
// present in Shadow Tree, and its value should be some identifier. Rules
// present outside of the shadow tree, must use the ::part pseudo-element,
// containing the same identifier as the argument. The global attribute part
// makes the element visible on just a single level of depth. When the shadow
// tree is nested, parts will be visible only to the parent of the shadow tree
// but not to its ancestor. Exporting parts further down is exactly what
// exportparts attribute is for. Attribute exportparts must be placed on a
// shadow Host, which is the element to which the shadow tree is attached. The
// value of the attribute should be a comma-separated list of part names present
// in the shadow tree and which should be made available via a DOM outside of
// the current structure.
func (e *WbrElement) Exportparts(s string) *WbrElement {
	values := strings.Split(s, ",")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("exportparts")
	if !ok {
		ds = newDelimitedBuilder[string](",")
		e.delimitedStrings.Set("exportparts", ds)
	}
	ds.Add(values...)
	return e
}

// The exportparts global attribute allows you to select and style elements
// existing in nested shadow trees, by exporting their part names. The shadow
// tree is an isolated structure where identifiers, classes, and styles cannot
// be reached by selectors or queries belonging to a regular DOM. To apply a
// style to an element living in a shadow tree, by CSS rule created outside of
// it, part global attribute has to be used. It has to be assigned to an element
// present in Shadow Tree, and its value should be some identifier. Rules
// present outside of the shadow tree, must use the ::part pseudo-element,
// containing the same identifier as the argument. The global attribute part
// makes the element visible on just a single level of depth. When the shadow
// tree is nested, parts will be visible only to the parent of the shadow tree
// but not to its ancestor. Exporting parts further down is exactly what
// exportparts attribute is for. Attribute exportparts must be placed on a
// shadow Host, which is the element to which the shadow tree is attached. The
// value of the attribute should be a comma-separated list of part names present
// in the shadow tree and which should be made available via a DOM outside of
// the current structure.
func (e *WbrElement) IfExportparts(condition bool, s string) *WbrElement {
	if condition {
		e.Exportparts(s)
	}
	return e
}

// The exportparts global attribute allows you to select and style elements
// existing in nested shadow trees, by exporting their part names. The shadow
// tree is an isolated structure where identifiers, classes, and styles cannot
// be reached by selectors or queries belonging to a regular DOM. To apply a
// style to an element living in a shadow tree, by CSS rule created outside of
// it, part global attribute has to be used. It has to be assigned to an element
// present in Shadow Tree, and its value should be some identifier. Rules
// present outside of the shadow tree, must use the ::part pseudo-element,
// containing the same identifier as the argument. The global attribute part
// makes the element visible on just a single level of depth. When the shadow
// tree is nested, parts will be visible only to the parent of the shadow tree
// but not to its ancestor. Exporting parts further down is exactly what
// exportparts attribute is for. Attribute exportparts must be placed on a
// shadow Host, which is the element to which the shadow tree is attached. The
// value of the attribute should be a comma-separated list of part names present
// in the shadow tree and which should be made available via a DOM outside of
// the current structure.
// Remove the values from the attribute Exportparts in the element.
func (e *WbrElement) ExportpartsRemove(s ...string) *WbrElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("exportparts")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// The hidden global attribute is a Boolean attribute indicating that the
// element is not yet, or is no longer, relevant. For example, it can be used to
// hide elements of the page that can't be used until the login process has been
// completed. Note that browsers typically implement hidden until found using
// content-visibility: hidden. This means that unlike elements in the hidden
// state, elements in the hidden until found state will have generated boxes,
// meaning that: the element will participate in page layout margin, borders,
// padding, and background for the element will be rendered. Also, the element
// needs to be affected by layout containment in order to be revealed. This
// means that if the element in the hidden until found state has a display value
// of none, contents, or inline, then the element will not be revealed by find
// in page or fragment navigation.
func (e *WbrElement) Hidden(c WbrHiddenChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("hidden", string(c))
	return e
}

type WbrHiddenChoice string

const (
	// set the element to the hidden state. Additionally, invalid values set the
	// element to the hidden state.
	WbrHiddenEmpty WbrHiddenChoice = ""
	// set the element to the hidden state. Additionally, invalid values set the
	// element to the hidden state.
	WbrHiddenHidden WbrHiddenChoice = "hidden"
	// the element is hidden but its content will be accessible to the browser's
	// "find in page" feature or to fragment navigation. When these features cause a
	// scroll to an element in a hidden until found subtree, the browser will fire a
	// beforematch event on the hidden element remove the hidden attribute from the
	// element scroll to the element
	//
	WbrHiddenUntilFound WbrHiddenChoice = "until-found"
)

// The hidden global attribute is a Boolean attribute indicating that the
// element is not yet, or is no longer, relevant. For example, it can be used to
// hide elements of the page that can't be used until the login process has been
// completed. Note that browsers typically implement hidden until found using
// content-visibility: hidden. This means that unlike elements in the hidden
// state, elements in the hidden until found state will have generated boxes,
// meaning that: the element will participate in page layout margin, borders,
// padding, and background for the element will be rendered. Also, the element
// needs to be affected by layout containment in order to be revealed. This
// means that if the element in the hidden until found state has a display value
// of none, contents, or inline, then the element will not be revealed by find
// in page or fragment navigation.
// Remove the attribute Hidden from the element.
func (e *WbrElement) HiddenRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("hidden")
	return e
}

// The id global attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *WbrElement) ID(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("id", s)
	return e
}

// The id global attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *WbrElement) IDF(format string, args ...any) *WbrElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// The id global attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *WbrElement) IfID(condition bool, s string) *WbrElement {
	if condition {
		e.ID(s)
	}
	return e
}

// The id global attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
func (e *WbrElement) IfIDF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// The id global attribute defines a unique identifier (ID) which must be unique
// in the whole document. Its purpose is to identify the element when linking
// (using a fragment identifier), scripting, or styling (with CSS).
// Remove the attribute ID from the element.
func (e *WbrElement) IDRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("id")
	return e
}

// The inert global attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *WbrElement) Inert() *WbrElement {
	e.InertSet(true)
	return e
}

// The inert global attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *WbrElement) IfInert(condition bool) *WbrElement {
	if condition {
		e.InertSet(true)
	}
	return e
}

// The inert global attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
// Set the attribute Inert to the value b explicitly.
func (e *WbrElement) InertSet(b bool) *WbrElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("inert", b)
	return e
}

// The inert global attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *WbrElement) IfSetInert(condition bool, b bool) *WbrElement {
	if condition {
		e.InertSet(b)
	}
	return e
}

// Remove the attribute Inert from the element.
// The inert global attribute is a Boolean attribute indicating that the browser
// will ignore the element. With the inert attribute, all of the element's flat
// tree descendants (such as modal <dialog>s) that don't otherwise escape
// inertness are ignored. The inert attribute also makes the browser ignore
// input events sent by the user, including focus-related events and events from
// assistive technologies. Specifically, inert does the following: Prevents the
// click event from being fired when the user clicks on the element. Prevents
// the focus event from being raised by preventing the element from gaining
// focus. Hides the element and its content from assistive technologies by
// excluding them from the accessibility tree.
func (e *WbrElement) InertRemove() *WbrElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("inert")
	return e
}

// The inputmode global attribute is an enumerated attribute that hints at the
// type of data that might be entered by the user while editing the element or
// its contents. This allows a browser to display an appropriate virtual
// keyboard. It is used primarily on <input> elements, but is usable on any
// element in contenteditable mode. It's important to understand that the
// inputmode attribute doesn't cause any validity requirements to be enforced on
// input. To require that input conforms to a particular data type, choose an
// appropriate <input> element type. For specific guidance on choosing <input>
// types, see the Values section.
func (e *WbrElement) Inputmode(c WbrInputmodeChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("inputmode", string(c))
	return e
}

type WbrInputmodeChoice string

const (
	// No virtual keyboard. For when the page implements its own keyboard input
	// control.
	WbrInputmodeNone WbrInputmodeChoice = "none"
	// Standard input keyboard for the user's current locale.
	WbrInputmodeEmpty WbrInputmodeChoice = ""
	// Standard input keyboard for the user's current locale.
	WbrInputmodeText WbrInputmodeChoice = "text"
	// Fractional numeric input keyboard containing the digits and decimal separator
	// for the user's locale (typically . or ,). Devices may or may not show a minus
	// key (-).
	WbrInputmodeDecimal WbrInputmodeChoice = "decimal"
	// Numeric input keyboard, but only requires the digits 0–9. Devices may or
	// may not show a minus key.
	WbrInputmodeNumeric WbrInputmodeChoice = "numeric"
	// A telephone keypad input, including the digits 0–9, the asterisk (*), and
	// the pound (#) key. Inputs that *require* a telephone number should typically
	// use <input type="tel"> instead.
	WbrInputmodeTel WbrInputmodeChoice = "tel"
	// A virtual keyboard optimized for search input. For instance, the
	// return/submit key may be labeled "Search", along with possible other
	// optimizations. Inputs that require a search query should typically use <input
	// type="search"> instead.
	WbrInputmodeSearch WbrInputmodeChoice = "search"
	// A virtual keyboard optimized for entering email addresses. Typically includes
	// the @character as well as other optimizations. Inputs that require email
	// addresses should typically use <input type="email"> instead.
	WbrInputmodeEmail WbrInputmodeChoice = "email"
	// A keypad optimized for entering URLs. This may have the / key more prominent,
	// for example. Enhanced features could include history access and so on. Inputs
	// that require a URL should typically use <input type="url"> instead.
	WbrInputmodeURL WbrInputmodeChoice = "url"
)

// The inputmode global attribute is an enumerated attribute that hints at the
// type of data that might be entered by the user while editing the element or
// its contents. This allows a browser to display an appropriate virtual
// keyboard. It is used primarily on <input> elements, but is usable on any
// element in contenteditable mode. It's important to understand that the
// inputmode attribute doesn't cause any validity requirements to be enforced on
// input. To require that input conforms to a particular data type, choose an
// appropriate <input> element type. For specific guidance on choosing <input>
// types, see the Values section.
// Remove the attribute Inputmode from the element.
func (e *WbrElement) InputmodeRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("inputmode")
	return e
}

// The is global attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *WbrElement) Is(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("is", s)
	return e
}

// The is global attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *WbrElement) IsF(format string, args ...any) *WbrElement {
	return e.Is(fmt.Sprintf(format, args...))
}

// The is global attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *WbrElement) IfIs(condition bool, s string) *WbrElement {
	if condition {
		e.Is(s)
	}
	return e
}

// The is global attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
func (e *WbrElement) IfIsF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Is(fmt.Sprintf(format, args...))
	}
	return e
}

// The is global attribute allows you to specify that a standard HTML element
// should behave like a defined custom built-in element (see Using custom
// elements for more details). This attribute can only be used if the specified
// custom element name has been successfully defined in the current document,
// and extends the element type it is being applied to.
// Remove the attribute Is from the element.
func (e *WbrElement) IsRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("is")
	return e
}

// The itemid global attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *WbrElement) Itemid(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemid", s)
	return e
}

// The itemid global attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *WbrElement) ItemidF(format string, args ...any) *WbrElement {
	return e.Itemid(fmt.Sprintf(format, args...))
}

// The itemid global attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *WbrElement) IfItemid(condition bool, s string) *WbrElement {
	if condition {
		e.Itemid(s)
	}
	return e
}

// The itemid global attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
func (e *WbrElement) IfItemidF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Itemid(fmt.Sprintf(format, args...))
	}
	return e
}

// The itemid global attribute provides microdata in the form of a unique,
// global identifier of an item.
//
// An itemid attribute can only be specified for an element that has both
// itemscope and itemtype attributes. Also, itemid can only be specified on
// elements that possess an itemscope attribute whose corresponding itemtype
// refers to or defines a vocabulary that supports global identifiers. The exact
// meaning of an itemtype's global identifier is provided by the definition of
// that identifier within the specified vocabulary. The vocabulary defines
// whether several items with the same global identifier can coexist and, if so,
// how items with the same identifier are handled.
// Remove the attribute Itemid from the element.
func (e *WbrElement) ItemidRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemid")
	return e
}

// The itemprop global attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *WbrElement) Itemprop(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemprop", s)
	return e
}

// The itemprop global attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *WbrElement) ItempropF(format string, args ...any) *WbrElement {
	return e.Itemprop(fmt.Sprintf(format, args...))
}

// The itemprop global attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *WbrElement) IfItemprop(condition bool, s string) *WbrElement {
	if condition {
		e.Itemprop(s)
	}
	return e
}

// The itemprop global attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
func (e *WbrElement) IfItempropF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Itemprop(fmt.Sprintf(format, args...))
	}
	return e
}

// The itemprop global attribute is used to add properties to an item. Every
// HTML element can have an itemprop attribute specified, and an itemprop
// consists of a name-value pair. Each name-value pair is called a property, and
// a group of one or more properties forms an item. Property values are either a
// string or a URL and can be associated with a very wide range of elements
// including <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>,
// <track>, and <video>.
// Remove the attribute Itemprop from the element.
func (e *WbrElement) ItempropRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemprop")
	return e
}

// Properties that are not descendants of an element with the itemscope
// attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *WbrElement) Itemref(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemref", s)
	return e
}

// Properties that are not descendants of an element with the itemscope
// attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *WbrElement) ItemrefF(format string, args ...any) *WbrElement {
	return e.Itemref(fmt.Sprintf(format, args...))
}

// Properties that are not descendants of an element with the itemscope
// attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *WbrElement) IfItemref(condition bool, s string) *WbrElement {
	if condition {
		e.Itemref(s)
	}
	return e
}

// Properties that are not descendants of an element with the itemscope
// attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
func (e *WbrElement) IfItemrefF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Itemref(fmt.Sprintf(format, args...))
	}
	return e
}

// Properties that are not descendants of an element with the itemscope
// attribute can be associated with an item using the global attribute itemref.
// itemref provides a list of element IDs (not itemids) elsewhere in the
// document, with additional properties The itemref attribute can only be
// specified on elements that have an itemscope attribute specified.
// Remove the attribute Itemref from the element.
func (e *WbrElement) ItemrefRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemref")
	return e
}

// The itemscope global attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *WbrElement) Itemscope() *WbrElement {
	e.ItemscopeSet(true)
	return e
}

// The itemscope global attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *WbrElement) IfItemscope(condition bool) *WbrElement {
	if condition {
		e.ItemscopeSet(true)
	}
	return e
}

// The itemscope global attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
// Set the attribute Itemscope to the value b explicitly.
func (e *WbrElement) ItemscopeSet(b bool) *WbrElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set("itemscope", b)
	return e
}

// The itemscope global attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *WbrElement) IfSetItemscope(condition bool, b bool) *WbrElement {
	if condition {
		e.ItemscopeSet(b)
	}
	return e
}

// Remove the attribute Itemscope from the element.
// The itemscope global attribute is used to add an item to a microdata DOM
// tree. Every HTML element can have an itemscope attribute specified, and an
// itemscope consists of a name-value pair. Each name-value pair is called a
// property, and a group of one or more properties forms an item. Property
// values are either a string or a URL and can be associated with a very wide
// range of elements including <audio>, <embed>, <iframe>, <img>, <link>,
// <object>, <source>, <track>, and <video>.
func (e *WbrElement) ItemscopeRemove() *WbrElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del("itemscope")
	return e
}

// The itemtype global attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *WbrElement) Itemtype(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("itemtype", s)
	return e
}

// The itemtype global attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *WbrElement) ItemtypeF(format string, args ...any) *WbrElement {
	return e.Itemtype(fmt.Sprintf(format, args...))
}

// The itemtype global attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *WbrElement) IfItemtype(condition bool, s string) *WbrElement {
	if condition {
		e.Itemtype(s)
	}
	return e
}

// The itemtype global attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
func (e *WbrElement) IfItemtypeF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Itemtype(fmt.Sprintf(format, args...))
	}
	return e
}

// The itemtype global attribute is used to add types to an item. Every HTML
// element can have an itemtype attribute specified, and an itemtype consists of
// a name-value pair. Each name-value pair is called a property, and a group of
// one or more properties forms an item. Property values are either a string or
// a URL and can be associated with a very wide range of elements including
// <audio>, <embed>, <iframe>, <img>, <link>, <object>, <source>, <track>, and
// <video>.
// Remove the attribute Itemtype from the element.
func (e *WbrElement) ItemtypeRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("itemtype")
	return e
}

// The lang global attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *WbrElement) Lang(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("lang", s)
	return e
}

// The lang global attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *WbrElement) LangF(format string, args ...any) *WbrElement {
	return e.Lang(fmt.Sprintf(format, args...))
}

// The lang global attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *WbrElement) IfLang(condition bool, s string) *WbrElement {
	if condition {
		e.Lang(s)
	}
	return e
}

// The lang global attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
func (e *WbrElement) IfLangF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Lang(fmt.Sprintf(format, args...))
	}
	return e
}

// The lang global attribute helps define the language of an element: the
// language that non-editable elements are written in or the language that
// editable elements should be written in by the user. The tag contains one
// single entry value in the format defines in the Tags for Identifying
// Languages (BCP47) IETF document. xml:lang has priority over it.
// Remove the attribute Lang from the element.
func (e *WbrElement) LangRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("lang")
	return e
}

// The nonce global attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *WbrElement) Nonce(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("nonce", s)
	return e
}

// The nonce global attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *WbrElement) NonceF(format string, args ...any) *WbrElement {
	return e.Nonce(fmt.Sprintf(format, args...))
}

// The nonce global attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *WbrElement) IfNonce(condition bool, s string) *WbrElement {
	if condition {
		e.Nonce(s)
	}
	return e
}

// The nonce global attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
func (e *WbrElement) IfNonceF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Nonce(fmt.Sprintf(format, args...))
	}
	return e
}

// The nonce global attribute is a unique identifier used to declare inline
// scripts and style elements to be used in a specific document. It is a
// cryptographic nonce (number used once) that is used by Content Security
// Policy to determine whether or not a given inline script is allowed to
// execute.
// Remove the attribute Nonce from the element.
func (e *WbrElement) NonceRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("nonce")
	return e
}

// The part global attribute contains a space-separated list of the part names
// of the element. Part names allows CSS to select and style specific elements
// in a shadow tree via the ::part pseudo-element.
func (e *WbrElement) Part(s string) *WbrElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("part")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("part", ds)
	}
	ds.Add(values...)
	return e
}

// The part global attribute contains a space-separated list of the part names
// of the element. Part names allows CSS to select and style specific elements
// in a shadow tree via the ::part pseudo-element.
func (e *WbrElement) IfPart(condition bool, s string) *WbrElement {
	if condition {
		e.Part(s)
	}
	return e
}

// The part global attribute contains a space-separated list of the part names
// of the element. Part names allows CSS to select and style specific elements
// in a shadow tree via the ::part pseudo-element.
// Remove the values from the attribute Part in the element.
func (e *WbrElement) PartRemove(s ...string) *WbrElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("part")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// The popover global attribute is used to designate an element as a popover
// element. Popover elements are hidden via display: none until opened via an
// invoking/control element (i.e. a <button> or <input type="button"> with a
// popovertarget attribute) or a HTMLElement.showPopover() call. When open,
// popover elements will appear above all other elements in the top layer, and
// won't be influenced by parent elements' position or overflow styling.
func (e *WbrElement) Popover(c WbrPopoverChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("popover", string(c))
	return e
}

type WbrPopoverChoice string

const (
	// Popovers that have the auto state can be "light dismissed" by selecting
	// outside the popover area, and generally only allow one popover to be
	// displayed on-screen at a time.
	WbrPopoverAuto WbrPopoverChoice = "auto"
	// Popovers that have the auto state can be "light dismissed" by selecting
	// outside the popover area, and generally only allow one popover to be
	// displayed on-screen at a time.
	WbrPopoverEmpty WbrPopoverChoice = ""
	// manual popovers must always be explicitly hidden, but allow for use cases
	// such as nested popovers in menus.
	WbrPopoverManual WbrPopoverChoice = "manual"
)

// The popover global attribute is used to designate an element as a popover
// element. Popover elements are hidden via display: none until opened via an
// invoking/control element (i.e. a <button> or <input type="button"> with a
// popovertarget attribute) or a HTMLElement.showPopover() call. When open,
// popover elements will appear above all other elements in the top layer, and
// won't be influenced by parent elements' position or overflow styling.
// Remove the attribute Popover from the element.
func (e *WbrElement) PopoverRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("popover")
	return e
}

// The role global attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *WbrElement) Role(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("role", s)
	return e
}

// The role global attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *WbrElement) RoleF(format string, args ...any) *WbrElement {
	return e.Role(fmt.Sprintf(format, args...))
}

// The role global attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *WbrElement) IfRole(condition bool, s string) *WbrElement {
	if condition {
		e.Role(s)
	}
	return e
}

// The role global attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
func (e *WbrElement) IfRoleF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Role(fmt.Sprintf(format, args...))
	}
	return e
}

// The role global attribute is used to define the purpose or state of an
// element to the browser, in order to facilitate assistive technology such as
// screen readers. It is a simple string value that can be used to describe the
// role of an element.
// Remove the attribute Role from the element.
func (e *WbrElement) RoleRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("role")
	return e
}

// The slot global attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *WbrElement) Slot(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("slot", s)
	return e
}

// The slot global attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *WbrElement) SlotF(format string, args ...any) *WbrElement {
	return e.Slot(fmt.Sprintf(format, args...))
}

// The slot global attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *WbrElement) IfSlot(condition bool, s string) *WbrElement {
	if condition {
		e.Slot(s)
	}
	return e
}

// The slot global attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
func (e *WbrElement) IfSlotF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Slot(fmt.Sprintf(format, args...))
	}
	return e
}

// The slot global attribute assigns a slot in a shadow DOM shadow tree to an
// element: An element with a slot attribute is assigned to the slot created by
// the <slot> element whose name attribute's value matches that slot attribute's
// value.
// Remove the attribute Slot from the element.
func (e *WbrElement) SlotRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("slot")
	return e
}

// The spellcheck global attribute is an enumerated attribute that defines
// whether the element may be checked for spelling errors. If this attribute is
// not set, its default value is element-type and browser-defined. This default
// value may also be inherited, which means that the element content will be
// checked for spelling errors only if its nearest ancestor has a spellcheck
// state of true. Security and privacy concerns Using spellchecking can have
// consequences for users' security and privacy. The specification does not
// regulate how spellchecking is done and the content of the element may be sent
// to a third party for spellchecking results (see enhanced spellchecking and
// "spell-jacking"). You should consider setting spellcheck to false for
// elements that can contain sensitive information.
func (e *WbrElement) Spellcheck(c WbrSpellcheckChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("spellcheck", string(c))
	return e
}

type WbrSpellcheckChoice string

const (
	// The element will be checked for spelling errors.
	WbrSpellcheckEmpty WbrSpellcheckChoice = ""
	// The element will be checked for spelling errors.
	WbrSpellcheckTrue WbrSpellcheckChoice = "true"
	// The element will not be checked for spelling errors.
	WbrSpellcheckFalse WbrSpellcheckChoice = "false"
)

// The spellcheck global attribute is an enumerated attribute that defines
// whether the element may be checked for spelling errors. If this attribute is
// not set, its default value is element-type and browser-defined. This default
// value may also be inherited, which means that the element content will be
// checked for spelling errors only if its nearest ancestor has a spellcheck
// state of true. Security and privacy concerns Using spellchecking can have
// consequences for users' security and privacy. The specification does not
// regulate how spellchecking is done and the content of the element may be sent
// to a third party for spellchecking results (see enhanced spellchecking and
// "spell-jacking"). You should consider setting spellcheck to false for
// elements that can contain sensitive information.
// Remove the attribute Spellcheck from the element.
func (e *WbrElement) SpellcheckRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("spellcheck")
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) StylePairs(pairs ...string) *WbrElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv = newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) Style(s string) *WbrElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) IfStyle(condition bool, s string) *WbrElement {
	if condition {
		e.Style(s)
	}
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) StyleAdd(k string, v string) *WbrElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) StyleAddF(k string, format string, args ...any) *WbrElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) IfStyleAdd(condition bool, k string, v string) *WbrElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
func (e *WbrElement) IfStyleAddF(condition bool, k string, format string, args ...any) *WbrElement {
	if condition {
		e.StyleAddF(k, format, args...)
	}
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
// Add the attributes in the map to the element.
func (e *WbrElement) StyleMap(m map[string]string) *WbrElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// The style global attribute is used to add styles to an element, such as
// color, font, size, and more. Styles are written in CSS.
// Remove the attribute Style from the element.
func (e *WbrElement) StyleRemove(keys ...string) *WbrElement {
	if e.keyValueStrings == nil {
		return e
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}

// The tabindex global attribute indicates if its element can be focused, and
// if/where it participates in sequential keyboard navigation (usually with the
// Tab key, hence the name). It accepts an integer as a value, with different
// results depending on the integer's value: a negative value (usually
// tabindex="-1") means that the element should be focusable, but should not be
// reachable via sequential keyboard navigation; a value of 0 (tabindex="0")
// means that the element should be focusable and reachable via sequential
// keyboard navigation, but its relative order is defined by the platform
// convention; a positive value means should be focusable and reachable via
// sequential keyboard navigation; its relative order is defined by the value of
// the attribute: the sequential follow the increasing number of the tabindex.
// If several elements share the same tabindex, their relative order follows
// their relative position in the document.
func (e *WbrElement) Tabindex(i int) *WbrElement {
	if e.intAttributes == nil {
		e.intAttributes = treemap.New[string, int]()
	}
	e.intAttributes.Set("tabindex", i)
	return e
}

// The tabindex global attribute indicates if its element can be focused, and
// if/where it participates in sequential keyboard navigation (usually with the
// Tab key, hence the name). It accepts an integer as a value, with different
// results depending on the integer's value: a negative value (usually
// tabindex="-1") means that the element should be focusable, but should not be
// reachable via sequential keyboard navigation; a value of 0 (tabindex="0")
// means that the element should be focusable and reachable via sequential
// keyboard navigation, but its relative order is defined by the platform
// convention; a positive value means should be focusable and reachable via
// sequential keyboard navigation; its relative order is defined by the value of
// the attribute: the sequential follow the increasing number of the tabindex.
// If several elements share the same tabindex, their relative order follows
// their relative position in the document.
func (e *WbrElement) IfTabindex(condition bool, i int) *WbrElement {
	if condition {
		e.Tabindex(i)
	}
	return e
}

// The tabindex global attribute indicates if its element can be focused, and
// if/where it participates in sequential keyboard navigation (usually with the
// Tab key, hence the name). It accepts an integer as a value, with different
// results depending on the integer's value: a negative value (usually
// tabindex="-1") means that the element should be focusable, but should not be
// reachable via sequential keyboard navigation; a value of 0 (tabindex="0")
// means that the element should be focusable and reachable via sequential
// keyboard navigation, but its relative order is defined by the platform
// convention; a positive value means should be focusable and reachable via
// sequential keyboard navigation; its relative order is defined by the value of
// the attribute: the sequential follow the increasing number of the tabindex.
// If several elements share the same tabindex, their relative order follows
// their relative position in the document.
// Remove the attribute Tabindex from the element.
func (e *WbrElement) TabindexRemove() *WbrElement {
	if e.intAttributes == nil {
		return e
	}
	e.intAttributes.Del("tabindex")
	return e
}

// The title global attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *WbrElement) Title(s string) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("title", s)
	return e
}

// The title global attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *WbrElement) TitleF(format string, args ...any) *WbrElement {
	return e.Title(fmt.Sprintf(format, args...))
}

// The title global attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *WbrElement) IfTitle(condition bool, s string) *WbrElement {
	if condition {
		e.Title(s)
	}
	return e
}

// The title global attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
func (e *WbrElement) IfTitleF(condition bool, format string, args ...any) *WbrElement {
	if condition {
		e.Title(fmt.Sprintf(format, args...))
	}
	return e
}

// The title global attribute contains text representing advisory information
// related to the element it belongs to. Such information can typically, but not
// necessarily, be presented to the user as a tooltip. The main use of the title
// attribute is to label <iframe> elements for assistive technology. The title
// attribute may also be used to label controls in data tables. The title
// attribute, when added to <link rel="stylesheet">, creates an alternate
// stylesheet. When defining an alternative style sheet with <link
// rel="alternate"> the attribute is required and must be set to a non-empty
// string. If included on the <abbr> opening tag, the title must be a full
// expansion of the abbreviation or acronym. Instead of using title, when
// possible, provide an expansion of the abbreviation or acronym in plain text
// on first use, using the <abbr> to mark up the abbreviation. This enables all
// users know what name or term the abbreviation or acronym shortens while
// providing a hint to user agents on how to announce the content. While title
// can be used to provide a programmatically associated label for an <input>
// element, this is not good practice. Use a <label> instead.
// Remove the attribute Title from the element.
func (e *WbrElement) TitleRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("title")
	return e
}

// The translate global attribute is an enumerated attribute that is used to
// specify whether an element's attribute values and the values of its Text node
// children are to be translated when the page is localized, or whether to leave
// them unchanged.
func (e *WbrElement) Translate(c WbrTranslateChoice) *WbrElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("translate", string(c))
	return e
}

type WbrTranslateChoice string

const (
	// indicates that the element should be translated when the page is localized.
	WbrTranslateEmpty WbrTranslateChoice = ""
	// indicates that the element should be translated when the page is localized.
	WbrTranslateYes WbrTranslateChoice = "yes"
	// indicates that the element must not be translated when the page is localized.
	WbrTranslateNo WbrTranslateChoice = "no"
)

// The translate global attribute is an enumerated attribute that is used to
// specify whether an element's attribute values and the values of its Text node
// children are to be translated when the page is localized, or whether to leave
// them unchanged.
// Remove the attribute Translate from the element.
func (e *WbrElement) TranslateRemove() *WbrElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("translate")
	return e
}
