// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements mathml annotation is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// This element is used to include comments or annotations within a MathML
// expression. It can be used to provide additional information about the
// expression, or to include comments for the author of the expression.
type MathMLAnnotationElement struct {
	*Element
}

// Create a new MathMLAnnotationElement element. This will create a new element
// with the tag "annotation" during rendering.
func MathMLAnnotation(children ...ElementRenderer) *MathMLAnnotationElement {
	e := NewElement("annotation", children...)
	e.IsSelfClosing = false
	e.Descendants = children
	return &MathMLAnnotationElement{Element: e}
}

func (e *MathMLAnnotationElement) Children(children ...ElementRenderer) *MathMLAnnotationElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *MathMLAnnotationElement) IfChildren(condition bool, children ...ElementRenderer) *MathMLAnnotationElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *MathMLAnnotationElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *MathMLAnnotationElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *MathMLAnnotationElement) BoolAttr(name string) *MathMLAnnotationElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *MathMLAnnotationElement) IfBoolAttr(condition bool, name string) *MathMLAnnotationElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *MathMLAnnotationElement) Attr(name, value string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *MathMLAnnotationElement) IfAttr(condition bool, name, value string) *MathMLAnnotationElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *MathMLAnnotationElement) Text(text string) *MathMLAnnotationElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *MathMLAnnotationElement) TextF(format string, args ...any) *MathMLAnnotationElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *MathMLAnnotationElement) IfText(condition bool, text string) *MathMLAnnotationElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *MathMLAnnotationElement) IfTextF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *MathMLAnnotationElement) Escaped(text string) *MathMLAnnotationElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *MathMLAnnotationElement) IfEscaped(condition bool, text string) *MathMLAnnotationElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *MathMLAnnotationElement) EscapedF(format string, args ...any) *MathMLAnnotationElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *MathMLAnnotationElement) IfEscapedF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

// The encoding of the semantic information in the annotation (e.g.,
// "application/x-tex")
func (e *MathMLAnnotationElement) Encoding(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("encoding", s)
	return e
}

// The encoding of the semantic information in the annotation (e.g.,
// "application/x-tex")
func (e *MathMLAnnotationElement) EncodingF(format string, args ...any) *MathMLAnnotationElement {
	return e.Encoding(fmt.Sprintf(format, args...))
}

// The encoding of the semantic information in the annotation (e.g.,
// "application/x-tex")
func (e *MathMLAnnotationElement) IfEncoding(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Encoding(s)
	}
	return e
}

// The encoding of the semantic information in the annotation (e.g.,
// "application/x-tex")
func (e *MathMLAnnotationElement) IfEncodingF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Encoding(fmt.Sprintf(format, args...))
	}
	return e
}

// The encoding of the semantic information in the annotation (e.g.,
// "application/x-tex")
// Remove the attribute Encoding from the element.
func (e *MathMLAnnotationElement) EncodingRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("encoding")
	return e
}

// This attribute specifies the name of the annotation.
func (e *MathMLAnnotationElement) Name(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("name", s)
	return e
}

// This attribute specifies the name of the annotation.
func (e *MathMLAnnotationElement) NameF(format string, args ...any) *MathMLAnnotationElement {
	return e.Name(fmt.Sprintf(format, args...))
}

// This attribute specifies the name of the annotation.
func (e *MathMLAnnotationElement) IfName(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Name(s)
	}
	return e
}

// This attribute specifies the name of the annotation.
func (e *MathMLAnnotationElement) IfNameF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Name(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the name of the annotation.
// Remove the attribute Name from the element.
func (e *MathMLAnnotationElement) NameRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("name")
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLAnnotationElement) Class(s string) *MathMLAnnotationElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLAnnotationElement) IfClass(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Class(s)
	}
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
// Remove the values from the attribute Class in the element.
func (e *MathMLAnnotationElement) ClassRemove(s ...string) *MathMLAnnotationElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
func (e *MathMLAnnotationElement) Dir(c MathMLAnnotationDirChoice) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dir", string(c))
	return e
}

type MathMLAnnotationDirChoice string

const (
	// left-to-right
	MathMLAnnotationDirLtr MathMLAnnotationDirChoice = "ltr"
	// right-to-left
	MathMLAnnotationDirRtl MathMLAnnotationDirChoice = "rtl"
)

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
// Remove the attribute Dir from the element.
func (e *MathMLAnnotationElement) DirRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dir")
	return e
}

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
func (e *MathMLAnnotationElement) Displaystyle(c MathMLAnnotationDisplaystyleChoice) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("displaystyle", string(c))
	return e
}

type MathMLAnnotationDisplaystyleChoice string

const (
	// displaystyle rules
	MathMLAnnotationDisplaystyleTrue MathMLAnnotationDisplaystyleChoice = "true"
	// not displaystyle rules
	MathMLAnnotationDisplaystyleFalse MathMLAnnotationDisplaystyleChoice = "false"
)

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
// Remove the attribute Displaystyle from the element.
func (e *MathMLAnnotationElement) DisplaystyleRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("displaystyle")
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLAnnotationElement) ID(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLAnnotationElement) IDF(format string, args ...any) *MathMLAnnotationElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLAnnotationElement) IfID(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.ID(s)
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLAnnotationElement) IfIDF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
// Remove the attribute ID from the element.
func (e *MathMLAnnotationElement) IDRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLAnnotationElement) Mathbackground(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathbackground", s)
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLAnnotationElement) MathbackgroundF(format string, args ...any) *MathMLAnnotationElement {
	return e.Mathbackground(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLAnnotationElement) IfMathbackground(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Mathbackground(s)
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLAnnotationElement) IfMathbackgroundF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Mathbackground(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
// Remove the attribute Mathbackground from the element.
func (e *MathMLAnnotationElement) MathbackgroundRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathbackground")
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLAnnotationElement) Mathcolor(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathcolor", s)
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLAnnotationElement) MathcolorF(format string, args ...any) *MathMLAnnotationElement {
	return e.Mathcolor(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLAnnotationElement) IfMathcolor(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Mathcolor(s)
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLAnnotationElement) IfMathcolorF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Mathcolor(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
// Remove the attribute Mathcolor from the element.
func (e *MathMLAnnotationElement) MathcolorRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathcolor")
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLAnnotationElement) MathsizeStr(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathsize", s)
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLAnnotationElement) MathsizeStrF(format string, args ...any) *MathMLAnnotationElement {
	return e.MathsizeStr(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLAnnotationElement) IfMathsizeStr(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.MathsizeStr(s)
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLAnnotationElement) IfMathsizeStrF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.MathsizeStr(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
// Remove the attribute MathsizeStr from the element.
func (e *MathMLAnnotationElement) MathsizeStrRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathsize")
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLAnnotationElement) Nonce(s string) *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("nonce", s)
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLAnnotationElement) NonceF(format string, args ...any) *MathMLAnnotationElement {
	return e.Nonce(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLAnnotationElement) IfNonce(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Nonce(s)
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLAnnotationElement) IfNonceF(condition bool, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.Nonce(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
// Remove the attribute Nonce from the element.
func (e *MathMLAnnotationElement) NonceRemove() *MathMLAnnotationElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("nonce")
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLAnnotationElement) Scriptlevel(i int) *MathMLAnnotationElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("scriptlevel", i)
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLAnnotationElement) IfScriptlevel(condition bool, i int) *MathMLAnnotationElement {
	if condition {
		e.Scriptlevel(i)
	}
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
// Remove the attribute Scriptlevel from the element.
func (e *MathMLAnnotationElement) ScriptlevelRemove() *MathMLAnnotationElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("scriptlevel")
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) StylePairs(pairs ...string) *MathMLAnnotationElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) Style(s string) *MathMLAnnotationElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) IfStyle(condition bool, s string) *MathMLAnnotationElement {
	if condition {
		e.Style(s)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) StyleAdd(k string, v string) *MathMLAnnotationElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) StyleAddF(k string, format string, args ...any) *MathMLAnnotationElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) IfStyleAdd(condition bool, k string, v string) *MathMLAnnotationElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLAnnotationElement) IfStyleAddF(condition bool, k string, format string, args ...any) *MathMLAnnotationElement {
	if condition {
		e.StyleAddF(k, format, args...)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Add the attributes in the map to the element.
func (e *MathMLAnnotationElement) StyleMap(m map[string]string) *MathMLAnnotationElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Remove the attribute Style from the element.
func (e *MathMLAnnotationElement) StyleRemove(keys ...string) *MathMLAnnotationElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLAnnotationElement) Tabindex(i int) *MathMLAnnotationElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("tabindex", i)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLAnnotationElement) IfTabindex(condition bool, i int) *MathMLAnnotationElement {
	if condition {
		e.Tabindex(i)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
// Remove the attribute Tabindex from the element.
func (e *MathMLAnnotationElement) TabindexRemove() *MathMLAnnotationElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("tabindex")
	return e
}
