// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements mathml mspace is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// This element is used to display a space.
type MathMLMspaceElement struct {
	*Element
}

// Create a new MathMLMspaceElement element. This will create a new element
// with the tag "mspace" during rendering.
func MathMLMspace(children ...ElementRenderer) *MathMLMspaceElement {
	e := NewElement("mspace", children...)
	e.IsSelfClosing = false
	e.Descendants = children
	return &MathMLMspaceElement{Element: e}
}

func (e *MathMLMspaceElement) Children(children ...ElementRenderer) *MathMLMspaceElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *MathMLMspaceElement) IfChildren(condition bool, children ...ElementRenderer) *MathMLMspaceElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *MathMLMspaceElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *MathMLMspaceElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *MathMLMspaceElement) BoolAttr(name string) *MathMLMspaceElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *MathMLMspaceElement) IfBoolAttr(condition bool, name string) *MathMLMspaceElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *MathMLMspaceElement) Attr(name, value string) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *MathMLMspaceElement) IfAttr(condition bool, name, value string) *MathMLMspaceElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *MathMLMspaceElement) Text(text string) *MathMLMspaceElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *MathMLMspaceElement) TextF(format string, args ...any) *MathMLMspaceElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *MathMLMspaceElement) IfText(condition bool, text string) *MathMLMspaceElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *MathMLMspaceElement) IfTextF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *MathMLMspaceElement) Escaped(text string) *MathMLMspaceElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *MathMLMspaceElement) IfEscaped(condition bool, text string) *MathMLMspaceElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *MathMLMspaceElement) EscapedF(format string, args ...any) *MathMLMspaceElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *MathMLMspaceElement) IfEscapedF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLMspaceElement) Class(s string) *MathMLMspaceElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
func (e *MathMLMspaceElement) IfClass(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.Class(s)
	}
	return e
}

// Assigns a class name or set of class names to an element. You may assign the
// same class name or names to any number of elements. If you specify multiple
// class names, they must be separated by whitespace characters.
// Remove the values from the attribute Class in the element.
func (e *MathMLMspaceElement) ClassRemove(s ...string) *MathMLMspaceElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
func (e *MathMLMspaceElement) Dir(c MathMLMspaceDirChoice) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("dir", string(c))
	return e
}

type MathMLMspaceDirChoice string

const (
	// left-to-right
	MathMLMspaceDirLtr MathMLMspaceDirChoice = "ltr"
	// right-to-left
	MathMLMspaceDirRtl MathMLMspaceDirChoice = "rtl"
)

// This attribute specifies the text directionality of the element, merely
// indicating what direction the text flows when surrounded by text with
// inherent directionality (such as Arabic or Hebrew). Possible values are ltr
// (left-to-right) and rtl (right-to-left).
// Remove the attribute Dir from the element.
func (e *MathMLMspaceElement) DirRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("dir")
	return e
}

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
func (e *MathMLMspaceElement) Displaystyle(c MathMLMspaceDisplaystyleChoice) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("displaystyle", string(c))
	return e
}

type MathMLMspaceDisplaystyleChoice string

const (
	// displaystyle rules
	MathMLMspaceDisplaystyleTrue MathMLMspaceDisplaystyleChoice = "true"
	// not displaystyle rules
	MathMLMspaceDisplaystyleFalse MathMLMspaceDisplaystyleChoice = "false"
)

// This attribute specifies whether the element should be rendered using
// displaystyle rules or not. Possible values are true and false.
// Remove the attribute Displaystyle from the element.
func (e *MathMLMspaceElement) DisplaystyleRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("displaystyle")
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMspaceElement) ID(s string) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMspaceElement) IDF(format string, args ...any) *MathMLMspaceElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMspaceElement) IfID(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.ID(s)
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
func (e *MathMLMspaceElement) IfIDF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute assigns a name to an element. This name must be unique in a
// document.
// Remove the attribute ID from the element.
func (e *MathMLMspaceElement) IDRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMspaceElement) Mathbackground(s string) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathbackground", s)
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMspaceElement) MathbackgroundF(format string, args ...any) *MathMLMspaceElement {
	return e.Mathbackground(fmt.Sprintf(format, args...))
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMspaceElement) IfMathbackground(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.Mathbackground(s)
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
func (e *MathMLMspaceElement) IfMathbackgroundF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.Mathbackground(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the background color of the element. Possible values
// are a color name or a color specification in the format defined in the CSS3
// Color Module [CSS3COLOR].
// Remove the attribute Mathbackground from the element.
func (e *MathMLMspaceElement) MathbackgroundRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathbackground")
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMspaceElement) Mathcolor(s string) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathcolor", s)
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMspaceElement) MathcolorF(format string, args ...any) *MathMLMspaceElement {
	return e.Mathcolor(fmt.Sprintf(format, args...))
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMspaceElement) IfMathcolor(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.Mathcolor(s)
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
func (e *MathMLMspaceElement) IfMathcolorF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.Mathcolor(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the color of the element. Possible values are a
// color name or a color specification in the format defined in the CSS3 Color
// Module [CSS3COLOR].
// Remove the attribute Mathcolor from the element.
func (e *MathMLMspaceElement) MathcolorRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathcolor")
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMspaceElement) MathsizeStr(s string) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("mathsize", s)
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMspaceElement) MathsizeStrF(format string, args ...any) *MathMLMspaceElement {
	return e.MathsizeStr(fmt.Sprintf(format, args...))
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMspaceElement) IfMathsizeStr(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.MathsizeStr(s)
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
func (e *MathMLMspaceElement) IfMathsizeStrF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.MathsizeStr(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute specifies the size of the element. Possible values are a
// dimension or a dimensionless number.
// Remove the attribute MathsizeStr from the element.
func (e *MathMLMspaceElement) MathsizeStrRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("mathsize")
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMspaceElement) Nonce(s string) *MathMLMspaceElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("nonce", s)
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMspaceElement) NonceF(format string, args ...any) *MathMLMspaceElement {
	return e.Nonce(fmt.Sprintf(format, args...))
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMspaceElement) IfNonce(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.Nonce(s)
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
func (e *MathMLMspaceElement) IfNonceF(condition bool, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.Nonce(fmt.Sprintf(format, args...))
	}
	return e
}

// This attribute declares a cryptographic nonce (number used once) that should
// be used by the server processing the element’s submission, and the
// resulting resource must be delivered with a Content-Security-Policy nonce
// attribute matching the value of the nonce attribute.
// Remove the attribute Nonce from the element.
func (e *MathMLMspaceElement) NonceRemove() *MathMLMspaceElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("nonce")
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLMspaceElement) Scriptlevel(i int) *MathMLMspaceElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("scriptlevel", i)
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
func (e *MathMLMspaceElement) IfScriptlevel(condition bool, i int) *MathMLMspaceElement {
	if condition {
		e.Scriptlevel(i)
	}
	return e
}

// This attribute specifies the script level of the element. Possible values are
// an integer between 0 and 7, inclusive.
// Remove the attribute Scriptlevel from the element.
func (e *MathMLMspaceElement) ScriptlevelRemove() *MathMLMspaceElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("scriptlevel")
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) StylePairs(pairs ...string) *MathMLMspaceElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) Style(s string) *MathMLMspaceElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) IfStyle(condition bool, s string) *MathMLMspaceElement {
	if condition {
		e.Style(s)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) StyleAdd(k string, v string) *MathMLMspaceElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) StyleAddF(k string, format string, args ...any) *MathMLMspaceElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) IfStyleAdd(condition bool, k string, v string) *MathMLMspaceElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
func (e *MathMLMspaceElement) IfStyleAddF(condition bool, k string, format string, args ...any) *MathMLMspaceElement {
	if condition {
		e.StyleAddF(k, format, args...)
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Add the attributes in the map to the element.
func (e *MathMLMspaceElement) StyleMap(m map[string]string) *MathMLMspaceElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// This attribute offers advisory information about the element for which it is
// set.
// Remove the attribute Style from the element.
func (e *MathMLMspaceElement) StyleRemove(keys ...string) *MathMLMspaceElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLMspaceElement) Tabindex(i int) *MathMLMspaceElement {
	if e.IntAttributes == nil {
		e.IntAttributes = treemap.New[string, int]()
	}
	e.IntAttributes.Set("tabindex", i)
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
func (e *MathMLMspaceElement) IfTabindex(condition bool, i int) *MathMLMspaceElement {
	if condition {
		e.Tabindex(i)
	}
	return e
}

// This attribute specifies the position of the current element in the tabbing
// order for the current document. This value must be a number between 0 and
// 32767. User agents should ignore leading zeros.
// Remove the attribute Tabindex from the element.
func (e *MathMLMspaceElement) TabindexRemove() *MathMLMspaceElement {
	if e.IntAttributes == nil {
		return e
	}
	e.IntAttributes.Del("tabindex")
	return e
}
