// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements svg defs is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <defs> SVG element is used to embed definitions that can be reused inside
// an SVG image.
type SVGDefsElement struct {
	*Element
}

// Create a new SVGDefsElement element. This will create a new element
// with the tag "defs" during rendering.
func SVGDefs(children ...ElementRenderer) *SVGDefsElement {
	e := NewElement("defs", children...)
	e.IsSelfClosing = false
	e.Descendants = children
	return &SVGDefsElement{Element: e}
}

func (e *SVGDefsElement) Children(children ...ElementRenderer) *SVGDefsElement {
	e.Descendants = append(e.Descendants, children...)
	return e
}

func (e *SVGDefsElement) IfChildren(condition bool, children ...ElementRenderer) *SVGDefsElement {
	if condition {
		e.Descendants = append(e.Descendants, children...)
	}
	return e
}

func (e *SVGDefsElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGDefsElement {
	if condition {
		e.Descendants = append(e.Descendants, trueChildren)
	} else {
		e.Descendants = append(e.Descendants, falseChildren)
	}
	return e
}

func (e *SVGDefsElement) BoolAttr(name string) *SVGDefsElement {
	if e.BoolAttributes == nil {
		e.BoolAttributes = treemap.New[string, bool]()
	}
	e.BoolAttributes.Set(name, true)
	return e
}

func (e *SVGDefsElement) IfBoolAttr(condition bool, name string) *SVGDefsElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGDefsElement) Attr(name, value string) *SVGDefsElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set(name, value)
	return e
}

func (e *SVGDefsElement) IfAttr(condition bool, name, value string) *SVGDefsElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGDefsElement) Text(text string) *SVGDefsElement {
	e.Descendants = append(e.Descendants, Text(text))
	return e
}

func (e *SVGDefsElement) TextF(format string, args ...any) *SVGDefsElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGDefsElement) IfText(condition bool, text string) *SVGDefsElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(text))
	}
	return e
}

func (e *SVGDefsElement) IfTextF(condition bool, format string, args ...any) *SVGDefsElement {
	if condition {
		e.Descendants = append(e.Descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGDefsElement) Escaped(text string) *SVGDefsElement {
	e.Descendants = append(e.Descendants, Escaped(text))
	return e
}

func (e *SVGDefsElement) IfEscaped(condition bool, text string) *SVGDefsElement {
	if condition {
		e.Descendants = append(e.Descendants, Escaped(text))
	}
	return e
}

func (e *SVGDefsElement) EscapedF(format string, args ...any) *SVGDefsElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGDefsElement) IfEscapedF(condition bool, format string, args ...any) *SVGDefsElement {
	if condition {
		e.Descendants = append(e.Descendants, EscapedF(format, args...))
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGDefsElement) ID(s string) *SVGDefsElement {
	if e.StringAttributes == nil {
		e.StringAttributes = treemap.New[string, string]()
	}
	e.StringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGDefsElement) IDF(format string, args ...any) *SVGDefsElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGDefsElement) IfID(condition bool, s string) *SVGDefsElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGDefsElement) IfIDF(condition bool, format string, args ...any) *SVGDefsElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGDefsElement) IDRemove() *SVGDefsElement {
	if e.StringAttributes == nil {
		return e
	}
	e.StringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGDefsElement) Class(s string) *SVGDefsElement {
	values := strings.Split(s, " ")
	if e.DelimitedStrings == nil {
		e.DelimitedStrings = treemap.New[string, *DelimitedBuilder[string]]()
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		ds = NewDelimitedBuilder[string](" ")
		e.DelimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGDefsElement) IfClass(condition bool, s string) *SVGDefsElement {
	if condition {
		e.Class(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the values from the attribute Class in the element.
func (e *SVGDefsElement) ClassRemove(s ...string) *SVGDefsElement {
	if e.DelimitedStrings == nil {
		return e
	}
	ds, ok := e.DelimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) StylePairs(pairs ...string) *SVGDefsElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		kv = NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) Style(s string) *SVGDefsElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) IfStyle(condition bool, s string) *SVGDefsElement {
	if condition {
		e.Style(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) StyleAdd(k string, v string) *SVGDefsElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) StyleAddF(k string, format string, args ...any) *SVGDefsElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) IfStyleAdd(condition bool, k string, v string) *SVGDefsElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGDefsElement) IfStyleAddF(condition bool, k string, format string, args ...any) *SVGDefsElement {
	if condition {
		e.StyleAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGDefsElement) StyleMap(m map[string]string) *SVGDefsElement {
	if e.KVStrings == nil {
		e.KVStrings = treemap.New[string, *KVBuilder]()
	}
	_, ok := e.KVStrings.Get("style")
	if !ok {
		kv := NewKVBuilder(":", ";")
		e.KVStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute Style from the element.
func (e *SVGDefsElement) StyleRemove(keys ...string) *SVGDefsElement {
	if e.KVStrings == nil {
		return e
	}
	kv, ok := e.KVStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
