// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements svg feColorMatrix is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feColorMatrix> SVG filter element changes colors based on a
// transformation matrix. Every pixel's color value (represented by an [R,G,B,A]
// vector) is matrix multiplied to create a new color.
type SVGFeColorMatrixElement struct {
	*Element
}

// Create a new SVGFeColorMatrixElement element. This will create a new element
// with the tag "feColorMatrix" during rendering.
func SVGFeColorMatrix(children ...ElementRenderer) *SVGFeColorMatrixElement {
	e := NewElement("feColorMatrix", children...)
	e.isSelfClosing = false
	e.descendants = children
	return &SVGFeColorMatrixElement{Element: e}
}

func (e *SVGFeColorMatrixElement) Children(children ...ElementRenderer) *SVGFeColorMatrixElement {
	e.descendants = append(e.descendants, children...)
	return e
}

func (e *SVGFeColorMatrixElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFeColorMatrixElement {
	if condition {
		e.descendants = append(e.descendants, children...)
	}
	return e
}

func (e *SVGFeColorMatrixElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFeColorMatrixElement {
	if condition {
		e.descendants = append(e.descendants, trueChildren)
	} else {
		e.descendants = append(e.descendants, falseChildren)
	}
	return e
}

func (e *SVGFeColorMatrixElement) BoolAttr(name string) *SVGFeColorMatrixElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set(name, true)
	return e
}

func (e *SVGFeColorMatrixElement) IfBoolAttr(condition bool, name string) *SVGFeColorMatrixElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFeColorMatrixElement) Attr(name, value string) *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set(name, value)
	return e
}

func (e *SVGFeColorMatrixElement) IfAttr(condition bool, name, value string) *SVGFeColorMatrixElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFeColorMatrixElement) Text(text string) *SVGFeColorMatrixElement {
	e.descendants = append(e.descendants, Text(text))
	return e
}

func (e *SVGFeColorMatrixElement) TextF(format string, args ...any) *SVGFeColorMatrixElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFeColorMatrixElement) IfText(condition bool, text string) *SVGFeColorMatrixElement {
	if condition {
		e.descendants = append(e.descendants, Text(text))
	}
	return e
}

func (e *SVGFeColorMatrixElement) IfTextF(condition bool, format string, args ...any) *SVGFeColorMatrixElement {
	if condition {
		e.descendants = append(e.descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFeColorMatrixElement) Escaped(text string) *SVGFeColorMatrixElement {
	e.descendants = append(e.descendants, Escaped(text))
	return e
}

func (e *SVGFeColorMatrixElement) IfEscaped(condition bool, text string) *SVGFeColorMatrixElement {
	if condition {
		e.descendants = append(e.descendants, Escaped(text))
	}
	return e
}

func (e *SVGFeColorMatrixElement) EscapedF(format string, args ...any) *SVGFeColorMatrixElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFeColorMatrixElement) IfEscapedF(condition bool, format string, args ...any) *SVGFeColorMatrixElement {
	if condition {
		e.descendants = append(e.descendants, EscapedF(format, args...))
	}
	return e
}

// The input for this filter.
func (e *SVGFeColorMatrixElement) In(s string) *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("in", s)
	return e
}

// The input for this filter.
func (e *SVGFeColorMatrixElement) InF(format string, args ...any) *SVGFeColorMatrixElement {
	return e.In(fmt.Sprintf(format, args...))
}

// The input for this filter.
func (e *SVGFeColorMatrixElement) IfIn(condition bool, s string) *SVGFeColorMatrixElement {
	if condition {
		e.In(s)
	}
	return e
}

// The input for this filter.
func (e *SVGFeColorMatrixElement) IfInF(condition bool, format string, args ...any) *SVGFeColorMatrixElement {
	if condition {
		e.In(fmt.Sprintf(format, args...))
	}
	return e
}

// The input for this filter.
// Remove the attribute In from the element.
func (e *SVGFeColorMatrixElement) InRemove() *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("in")
	return e
}

// The type of matrix operation.
func (e *SVGFeColorMatrixElement) Type(c SVGFeColorMatrixTypeChoice) *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("type", string(c))
	return e
}

type SVGFeColorMatrixTypeChoice string

const (
	// The type of matrix operation.
	SVGFeColorMatrixTypeMatrix SVGFeColorMatrixTypeChoice = "matrix"
	// The type of matrix operation.
	SVGFeColorMatrixTypeSaturate SVGFeColorMatrixTypeChoice = "saturate"
	// The type of matrix operation.
	SVGFeColorMatrixTypeHueRotate SVGFeColorMatrixTypeChoice = "hueRotate"
	// The type of matrix operation.
	SVGFeColorMatrixTypeLuminanceToAlpha SVGFeColorMatrixTypeChoice = "luminanceToAlpha"
)

// The type of matrix operation.
// Remove the attribute Type from the element.
func (e *SVGFeColorMatrixElement) TypeRemove() *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("type")
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFeColorMatrixElement) Values(s string) *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("values", s)
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFeColorMatrixElement) ValuesF(format string, args ...any) *SVGFeColorMatrixElement {
	return e.Values(fmt.Sprintf(format, args...))
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFeColorMatrixElement) IfValues(condition bool, s string) *SVGFeColorMatrixElement {
	if condition {
		e.Values(s)
	}
	return e
}

// The list of one or more numbers that represent the matrix.
func (e *SVGFeColorMatrixElement) IfValuesF(condition bool, format string, args ...any) *SVGFeColorMatrixElement {
	if condition {
		e.Values(fmt.Sprintf(format, args...))
	}
	return e
}

// The list of one or more numbers that represent the matrix.
// Remove the attribute Values from the element.
func (e *SVGFeColorMatrixElement) ValuesRemove() *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("values")
	return e
}

// Specifies a unique id for an element
func (e *SVGFeColorMatrixElement) ID(s string) *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFeColorMatrixElement) IDF(format string, args ...any) *SVGFeColorMatrixElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFeColorMatrixElement) IfID(condition bool, s string) *SVGFeColorMatrixElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFeColorMatrixElement) IfIDF(condition bool, format string, args ...any) *SVGFeColorMatrixElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGFeColorMatrixElement) IDRemove() *SVGFeColorMatrixElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFeColorMatrixElement) Class(s string) *SVGFeColorMatrixElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFeColorMatrixElement) IfClass(condition bool, s string) *SVGFeColorMatrixElement {
	if condition {
		e.Class(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the values from the attribute Class in the element.
func (e *SVGFeColorMatrixElement) ClassRemove(s ...string) *SVGFeColorMatrixElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) StylePairs(pairs ...string) *SVGFeColorMatrixElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv = newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) Style(s string) *SVGFeColorMatrixElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) IfStyle(condition bool, s string) *SVGFeColorMatrixElement {
	if condition {
		e.Style(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) StyleAdd(k string, v string) *SVGFeColorMatrixElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) StyleAddF(k string, format string, args ...any) *SVGFeColorMatrixElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) IfStyleAdd(condition bool, k string, v string) *SVGFeColorMatrixElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeColorMatrixElement) IfStyleAddF(condition bool, k string, format string, args ...any) *SVGFeColorMatrixElement {
	if condition {
		e.StyleAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFeColorMatrixElement) StyleMap(m map[string]string) *SVGFeColorMatrixElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute Style from the element.
func (e *SVGFeColorMatrixElement) StyleRemove(keys ...string) *SVGFeColorMatrixElement {
	if e.keyValueStrings == nil {
		return e
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
