// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements svg view is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <view> SVG element is used to define a view into a &lt;svg&gt; element.
// It is partially deprecated in SVG 2.0 and should generally not be used.
type SVGViewElement struct {
	*Element
}

// Create a new SVGViewElement element. This will create a new element
// with the tag "view" during rendering.
func SVGView(children ...ElementRenderer) *SVGViewElement {
	e := NewElement("view", children...)
	e.isSelfClosing = false
	e.descendants = children
	return &SVGViewElement{Element: e}
}

func (e *SVGViewElement) Children(children ...ElementRenderer) *SVGViewElement {
	e.descendants = append(e.descendants, children...)
	return e
}

func (e *SVGViewElement) IfChildren(condition bool, children ...ElementRenderer) *SVGViewElement {
	if condition {
		e.descendants = append(e.descendants, children...)
	}
	return e
}

func (e *SVGViewElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGViewElement {
	if condition {
		e.descendants = append(e.descendants, trueChildren)
	} else {
		e.descendants = append(e.descendants, falseChildren)
	}
	return e
}

func (e *SVGViewElement) BoolAttr(name string) *SVGViewElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, bool]()
	}
	e.boolAttributes.Set(name, true)
	return e
}

func (e *SVGViewElement) IfBoolAttr(condition bool, name string) *SVGViewElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGViewElement) Attr(name, value string) *SVGViewElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set(name, value)
	return e
}

func (e *SVGViewElement) IfAttr(condition bool, name, value string) *SVGViewElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGViewElement) Text(text string) *SVGViewElement {
	e.descendants = append(e.descendants, Text(text))
	return e
}

func (e *SVGViewElement) TextF(format string, args ...any) *SVGViewElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGViewElement) IfText(condition bool, text string) *SVGViewElement {
	if condition {
		e.descendants = append(e.descendants, Text(text))
	}
	return e
}

func (e *SVGViewElement) IfTextF(condition bool, format string, args ...any) *SVGViewElement {
	if condition {
		e.descendants = append(e.descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGViewElement) Escaped(text string) *SVGViewElement {
	e.descendants = append(e.descendants, Escaped(text))
	return e
}

func (e *SVGViewElement) IfEscaped(condition bool, text string) *SVGViewElement {
	if condition {
		e.descendants = append(e.descendants, Escaped(text))
	}
	return e
}

func (e *SVGViewElement) EscapedF(format string, args ...any) *SVGViewElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGViewElement) IfEscapedF(condition bool, format string, args ...any) *SVGViewElement {
	if condition {
		e.descendants = append(e.descendants, EscapedF(format, args...))
	}
	return e
}

// The position and size of the viewport (the viewBox) is defined by the viewBox
// Attribute.
func (e *SVGViewElement) ViewBox(s string) *SVGViewElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("viewBox", s)
	return e
}

// The position and size of the viewport (the viewBox) is defined by the viewBox
// Attribute.
func (e *SVGViewElement) ViewBoxF(format string, args ...any) *SVGViewElement {
	return e.ViewBox(fmt.Sprintf(format, args...))
}

// The position and size of the viewport (the viewBox) is defined by the viewBox
// Attribute.
func (e *SVGViewElement) IfViewBox(condition bool, s string) *SVGViewElement {
	if condition {
		e.ViewBox(s)
	}
	return e
}

// The position and size of the viewport (the viewBox) is defined by the viewBox
// Attribute.
func (e *SVGViewElement) IfViewBoxF(condition bool, format string, args ...any) *SVGViewElement {
	if condition {
		e.ViewBox(fmt.Sprintf(format, args...))
	}
	return e
}

// The position and size of the viewport (the viewBox) is defined by the viewBox
// Attribute.
// Remove the attribute ViewBox from the element.
func (e *SVGViewElement) ViewBoxRemove() *SVGViewElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("viewBox")
	return e
}

// Specifies a unique id for an element
func (e *SVGViewElement) ID(s string) *SVGViewElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGViewElement) IDF(format string, args ...any) *SVGViewElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGViewElement) IfID(condition bool, s string) *SVGViewElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGViewElement) IfIDF(condition bool, format string, args ...any) *SVGViewElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGViewElement) IDRemove() *SVGViewElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGViewElement) Class(s string) *SVGViewElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGViewElement) IfClass(condition bool, s string) *SVGViewElement {
	if condition {
		e.Class(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the values from the attribute Class in the element.
func (e *SVGViewElement) ClassRemove(s ...string) *SVGViewElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) StylePairs(pairs ...string) *SVGViewElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv = newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) Style(s string) *SVGViewElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) IfStyle(condition bool, s string) *SVGViewElement {
	if condition {
		e.Style(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) StyleAdd(k string, v string) *SVGViewElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) StyleAddF(k string, format string, args ...any) *SVGViewElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) IfStyleAdd(condition bool, k string, v string) *SVGViewElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGViewElement) IfStyleAddF(condition bool, k string, format string, args ...any) *SVGViewElement {
	if condition {
		e.StyleAddF(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGViewElement) StyleMap(m map[string]string) *SVGViewElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute Style from the element.
func (e *SVGViewElement) StyleRemove(keys ...string) *SVGViewElement {
	if e.keyValueStrings == nil {
		return e
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
