// Code generated by speckles. DO NOT EDIT.
// Source: generator/templates/element.go.tmpl

// Package elements svg feMerge is generated from configuration file.
package elements

import (
	"fmt"
	"sort"
	"strings"

	"github.com/igrmk/treemap/v2"
)

// The <feMerge> SVG element allows filter effects to be applied concurrently
// instead of sequentially.
type SVGFeMergeElement struct {
	*Element
}

// Create a new SVGFeMergeElement element. This will create a new element
// with the tag "feMerge" during rendering.
func SVGFeMerge(children ...ElementRenderer) *SVGFeMergeElement {
	e := NewElement("feMerge", children...)
	e.isSelfClosing = false
	e.descendants = children
	return &SVGFeMergeElement{Element: e}
}

func (e *SVGFeMergeElement) Children(children ...ElementRenderer) *SVGFeMergeElement {
	e.descendants = append(e.descendants, children...)
	return e
}

func (e *SVGFeMergeElement) IfChildren(condition bool, children ...ElementRenderer) *SVGFeMergeElement {
	if condition {
		e.descendants = append(e.descendants, children...)
	}
	return e
}

func (e *SVGFeMergeElement) TernChildren(condition bool, trueChildren, falseChildren ElementRenderer) *SVGFeMergeElement {
	if condition {
		e.descendants = append(e.descendants, trueChildren)
	} else {
		e.descendants = append(e.descendants, falseChildren)
	}
	return e
}

func (e *SVGFeMergeElement) BoolAttr(name string) *SVGFeMergeElement {
	if e.boolAttributes == nil {
		e.boolAttributes = treemap.New[string, struct{}]()
	}
	e.boolAttributes.Set(name, struct{}{})
	return e
}

func (e *SVGFeMergeElement) BoolAttrRemove(name string) *SVGFeMergeElement {
	if e.boolAttributes == nil {
		return e
	}
	e.boolAttributes.Del(name)
	return e
}

func (e *SVGFeMergeElement) IfBoolAttr(condition bool, name string) *SVGFeMergeElement {
	if condition {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFeMergeElement) BoolAttrf(format string, args ...any) *SVGFeMergeElement {
	return e.BoolAttr(fmt.Sprintf(format, args...))
}

func (e *SVGFeMergeElement) IfBoolAttrf(condition bool, format string, args ...any) *SVGFeMergeElement {
	if condition {
		e.BoolAttrf(format, args...)
	}
	return e
}

func (e *SVGFeMergeElement) BoolAttrs(names ...string) *SVGFeMergeElement {
	for _, name := range names {
		e.BoolAttr(name)
	}
	return e
}

func (e *SVGFeMergeElement) IfBoolAttrs(condition bool, names ...string) *SVGFeMergeElement {
	if condition {
		e.BoolAttrs(names...)
	}
	return e
}

func (e *SVGFeMergeElement) Attr(name, value string) *SVGFeMergeElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set(name, value)
	return e
}

func (e *SVGFeMergeElement) IfAttr(condition bool, name, value string) *SVGFeMergeElement {
	if condition {
		e.Attr(name, value)
	}
	return e
}

func (e *SVGFeMergeElement) Attrf(name, format string, args ...any) *SVGFeMergeElement {
	return e.Attr(name, fmt.Sprintf(format, args...))
}

func (e *SVGFeMergeElement) IfAttrf(condition bool, name, format string, args ...any) *SVGFeMergeElement {
	if condition {
		e.Attrf(name, format, args...)
	}
	return e
}

func (e *SVGFeMergeElement) Attrs(attrs ...string) *SVGFeMergeElement {
	if len(attrs)%2 != 0 {
		panic("attrs must be a multiple of 2")
	}
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	for i := 0; i < len(attrs); i += 2 {
		k := attrs[i]
		v := attrs[i+1]
		e.stringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGFeMergeElement) IfAttrs(condition bool, attrs ...string) *SVGFeMergeElement {
	if condition {
		e.Attrs(attrs...)
	}
	return e
}

func (e *SVGFeMergeElement) AttrsMap(attrs map[string]string) *SVGFeMergeElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	for k, v := range attrs {
		e.stringAttributes.Set(k, v)
	}
	return e
}

func (e *SVGFeMergeElement) IfAttrsMap(condition bool, attrs map[string]string) *SVGFeMergeElement {
	if condition {
		e.AttrsMap(attrs)
	}
	return e
}

func (e *SVGFeMergeElement) Text(text string) *SVGFeMergeElement {
	e.descendants = append(e.descendants, Text(text))
	return e
}

func (e *SVGFeMergeElement) Textf(format string, args ...any) *SVGFeMergeElement {
	return e.Text(fmt.Sprintf(format, args...))
}

func (e *SVGFeMergeElement) IfText(condition bool, text string) *SVGFeMergeElement {
	if condition {
		e.descendants = append(e.descendants, Text(text))
	}
	return e
}

func (e *SVGFeMergeElement) IfTextf(condition bool, format string, args ...any) *SVGFeMergeElement {
	if condition {
		e.descendants = append(e.descendants, Text(fmt.Sprintf(format, args...)))
	}
	return e
}

func (e *SVGFeMergeElement) Escaped(text string) *SVGFeMergeElement {
	e.descendants = append(e.descendants, Escaped(text))
	return e
}

func (e *SVGFeMergeElement) IfEscaped(condition bool, text string) *SVGFeMergeElement {
	if condition {
		e.descendants = append(e.descendants, Escaped(text))
	}
	return e
}

func (e *SVGFeMergeElement) Escapedf(format string, args ...any) *SVGFeMergeElement {
	return e.Escaped(fmt.Sprintf(format, args...))
}

func (e *SVGFeMergeElement) IfEscapedf(condition bool, format string, args ...any) *SVGFeMergeElement {
	if condition {
		e.descendants = append(e.descendants, Escapedf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFeMergeElement) ID(s string) *SVGFeMergeElement {
	if e.stringAttributes == nil {
		e.stringAttributes = treemap.New[string, string]()
	}
	e.stringAttributes.Set("id", s)
	return e
}

// Specifies a unique id for an element
func (e *SVGFeMergeElement) IDf(format string, args ...any) *SVGFeMergeElement {
	return e.ID(fmt.Sprintf(format, args...))
}

// Specifies a unique id for an element
func (e *SVGFeMergeElement) IfID(condition bool, s string) *SVGFeMergeElement {
	if condition {
		e.ID(s)
	}
	return e
}

// Specifies a unique id for an element
func (e *SVGFeMergeElement) IfIDf(condition bool, format string, args ...any) *SVGFeMergeElement {
	if condition {
		e.ID(fmt.Sprintf(format, args...))
	}
	return e
}

// Specifies a unique id for an element
// Remove the attribute ID from the element.
func (e *SVGFeMergeElement) IDRemove() *SVGFeMergeElement {
	if e.stringAttributes == nil {
		return e
	}
	e.stringAttributes.Del("id")
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFeMergeElement) Class(s string) *SVGFeMergeElement {
	values := strings.Split(s, " ")
	if e.delimitedStrings == nil {
		e.delimitedStrings = treemap.New[string, *delimitedBuilder[string]]()
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		ds = newDelimitedBuilder[string](" ")
		e.delimitedStrings.Set("class", ds)
	}
	ds.Add(values...)
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
func (e *SVGFeMergeElement) IfClass(condition bool, s string) *SVGFeMergeElement {
	if condition {
		e.Class(s)
	}
	return e
}

// Specifies one or more classnames for an element (refers to a class in a style
// sheet)
// Remove the values from the attribute Class in the element.
func (e *SVGFeMergeElement) ClassRemove(s ...string) *SVGFeMergeElement {
	if e.delimitedStrings == nil {
		return e
	}
	ds, ok := e.delimitedStrings.Get("class")
	if !ok {
		return e
	}
	ds.Remove(s...)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) StylePairs(pairs ...string) *SVGFeMergeElement {
	if len(pairs) == 0 || len(pairs)%2 != 0 {
		panic("StylePairs requires an even number of arguments representing key-value pairs.")
	}
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv = newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	for i := 0; i < len(pairs)-1; i += 2 {
		key := strings.TrimSpace(pairs[i])
		if key == "" {
			panic("empty key in key-value pairs.")
		}
		value := strings.TrimSpace(pairs[i+1])
		kv.Add(key, value)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) Style(s string) *SVGFeMergeElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	s = strings.TrimRight(s, ";")
	kvPairs := strings.Split(s, ";")
	for _, pair := range kvPairs {
		parts := strings.SplitN(pair, ":", 2)
		if len(parts) != 2 {
			panic(fmt.Sprintf("invalid key-value pair: %q", pair))
		}
		e.StylePairs(parts[0], parts[1])
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) IfStyle(condition bool, s string) *SVGFeMergeElement {
	if condition {
		e.Style(s)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) StyleAdd(k string, v string) *SVGFeMergeElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	e.StylePairs(k, v)
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) StyleAddf(k string, format string, args ...any) *SVGFeMergeElement {
	return e.StyleAdd(k, fmt.Sprintf(format, args...))
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) IfStyleAdd(condition bool, k string, v string) *SVGFeMergeElement {
	if condition {
		e.StyleAdd(k, v)
	}
	return e
}

// Specifies an inline CSS style for an element
func (e *SVGFeMergeElement) IfStyleAddf(condition bool, k string, format string, args ...any) *SVGFeMergeElement {
	if condition {
		e.StyleAddf(k, format, args...)
	}
	return e
}

// Specifies an inline CSS style for an element
// Add the attributes in the map to the element.
func (e *SVGFeMergeElement) StyleMap(m map[string]string) *SVGFeMergeElement {
	if e.keyValueStrings == nil {
		e.keyValueStrings = treemap.New[string, *keyValueBuilder]()
	}
	_, ok := e.keyValueStrings.Get("style")
	if !ok {
		kv := newKVBuilder(":", ";")
		e.keyValueStrings.Set("style", kv)
	}
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		e.StylePairs(k, m[k])
	}
	return e
}

// Specifies an inline CSS style for an element
// Remove the attribute Style from the element.
func (e *SVGFeMergeElement) StyleRemove(keys ...string) *SVGFeMergeElement {
	if e.keyValueStrings == nil {
		return e
	}
	kv, ok := e.keyValueStrings.Get("style")
	if !ok {
		return e
	}
	kv.Remove(keys...)
	return e
}
